gcc-5.x: avoid hhvm build failure
Summary:
gcc 5.3.1 was failing with:

  hphp/runtime/ext/iconv/ext_iconv.cpp:
  In function 'HPHP::Variant HPHP::f_iconv_mime_encode(
    const HPHP::String&, const HPHP::String&, const HPHP::Variant&)':
  hphp/runtime/ext/iconv/ext_iconv.cpp:171:56: error:
    array subscript is above array bounds [-Werror=array-bounds]

This looks to be an erroneous warning was there should only be
NUL terminated strings passed into this function.
Here we provide more info to the compiler about the limits of the data
that memcpy() reads, which are enforced previously with strncasemp().

Reviewed By: markw65, Orvid

Differential Revision: D3322792

fbshipit-source-id: 864bd77d720551eeb237afa5e7889c29ffdf284b