Remove implicit integer conversion in `SparseByteSet`
Summary:
Found when tried to use `SparseByteSet`. Compiler wasn't happy,
because `-Wimplicit-int-conversion` flag was set.

```
error: implicit conversion loses integer precision: 'int' to 'uint8_t' (aka 'unsigned char') [-Werror,-Wimplicit-int-conversion]
        dense_[sparse_[i]] = last_element;
```

Reviewed By: marksantaniello, DenisYaroshevskiy

Differential Revision: D60284815

fbshipit-source-id: 5a70acd40f16bb5d31c3f361de1954a55af4d05d