Fix clang17 -Wsign-compare in OpenSSLUtils::getPeerAddressFromX509StoreCtx
Summary:
Fixes a Windows clang 15.0.5 -> 17.0.6 `-Werror,-Wsign-compare` build break
surfaced by the toolchain switch in D110606117 (T281071588).

`*addrLen` is a `socklen_t` (signed `int` on Windows) and is compared against
`sizeof(*addrStorage)` (unsigned `size_t`):

```
folly/io/async/ssl/OpenSSLUtils.cpp(90,18): error: comparison of integers of different signs: 'socklen_t' (aka 'int') and 'unsigned long long' [-Werror,-Wsign-compare]
```

`*addrLen` was just set by a successful `getpeername`, so it is non-negative;
cast it to `size_t` for the bounds `CHECK`. Applied to both the `fbcode/folly`
and `xplat/folly` copies.

Reviewed By: meyering

Differential Revision: D113783789

fbshipit-source-id: dffef708fd94eb8d3498102794f23bffc2639605