clean up non-existent target
Summary:
D16574809 (https://github.com/facebook/hhvm/commit/d41c1cc41d848ae8b56619f1daac97a1ee4c0370) added 'hphp/hack/test/Cargo.toml' which refers to a binary `test_facts_parse` with `path=rust/facts_parse.rs`.

this leads to
```
error: couldn't read test/rust/facts_parse.rs: No such file or directory (os error 2)
```
when you run `cd fbsource &&cargo check --manifest-path fbcode/hphp/hack/Cargo.toml`.

the `.toml` file is not auto-generated. the source file `facts_parse.rs` was removed in D33722419 (https://github.com/facebook/hhvm/commit/b2ea9e104e8687a607523016417fc68da520f4b4).

in this diff I remove 'hphp/hack/test/Cargo.toml' and remove "hphp/hack/test" from 'hphp/hack.cargo/Cargo.toml.ocaml_build'.

Reviewed By: aorenste

Differential Revision: D39412960

fbshipit-source-id: 578952b6a0eee014e7b0d2dda0e0610c001f064f