anyhow backtrace
Summary:
anyhow backtraces are tricky!

The docs say the "anyhow::Error::backtrace" method is available only on nightly or crate feature backtrace. https://docs.rs/anyhow/1.0.64/anyhow/struct.Error.html#method.backtrace

edwinsmith recently wrote a diff which got rid of `#[backtrace]` for thiserror in some cases D39385365.

There's been a version bump of thiserror and anyhow crates which depend on the latest fbcode.

Two diffs by zhyty D39210667, D39187214 failed with the message
```
error[E0599]: no method named `backtrace` found for struct `anyhow::Error` in the current scope
   --> src/utils/hh24_types/hh24_types.rs:544:43
    |
544 |         let backtrace = format!("{}", err.backtrace());
    |                                           ^^^^^^^^^ method not found in `anyhow::Error`
```

I conjecture the problem is that we're not picking up the right flags for the anyhow dependency, at least not in some of our build targets.

The code in question is solely used for StringifiedError, which is solely used by decl-ipc, which is going away.

Therefore: let me reduce our exposure to anyhow backtrace build issues. I don't want to mess with crate dependency flags. The docs for anyhow::Error explain that print format `{:?}` will include backtrace. So I'll just use that. (It will result in the causes being printed twice, which isn't elegant, but I kind of don't want to invest more time here).

Reviewed By: zhyty

Differential Revision: D39438909

fbshipit-source-id: 776e15d04cdf9771884165571879f0df60601807