fix watchman failure in saved-state tests
Summary:
Some of our saved-state integration tests are failing, e.g.
https://our.intern.facebook.com/intern/everpaste/?handle=GC9DvQKedamReskDAMKPq61pVMkUbr0LAAAz
```
F hphp/hack/test/integration:integration_save_state - test_interrupt (hphp.hack.test.integration.test_save_state.SavedStateCommonTests) 5.852 172/514 (failed)
Test failed:
> AssertionError: 'Using watchman' not found in '/tmp/tmp7zfmlf2v/repo/hh.conf:\n\n# some comment\nuse_mini_state = true\nuse_watchman = true\nwatchman_subscribe_v2 = true\nlazy_decl = true\nlazy_parse = true\nlazy_init2 = true\nuse_watchman = true\ninterrupt_on_watchman = true\ninterrupt_on_client = true\nwatchman_subscribe_v2 = true\n\n[2019-05-28 12:58:51.356] Version:  Wed Dec 31 16:00:00 1969\n[2019-05-28 12:58:51.356] Hostname: devvm158.prn3.facebook.com\n[2019-05-28 12:58:51.390] Watchman init: Watchman_sig.Types.Watchman_error("RootResolveError: unable to resolve root /tmp/tmp7zfmlf2v/repo: failed to parse json from /tmp/tmp7zfmlf2v/repo/.watchmanconfig: \'[\' or \'{\' expected near end of file")\nRaised at file "/data/users/ljw/fbsource/fbcode/hphp/hack/src/watchman/watchman.ml", line 56, characters 6-11\nCalled from file "/data/users/ljw/fbsource/fbcode/hphp/hack/src/watchman/watchman.ml", line 78, characters 4-28\nCalled from file "/data/users/ljw/fbsource/fbcode/hphp/hack/src/watchman/watchman.ml", line 510, characters 8-101\nCalled from file "list.ml", line 96, characters 24-34\nCalled from file "/data/users/ljw/fbsource/fbcode/hphp/hack/src/watchman/watchman.ml", line 506, characters 4-1023\nCalled from file "/data/users/ljw/fbsource/fbcode/hphp/hack/src/watchman/watchman.ml", line 98, characters 6-10\n\n
```

This error message shows that watchman has detected a problem with the .watchmanconfig and is telling us about it. In our normal real www repo, .watchmanconfig works fine. In our test repos, there are several places where we write a .watchmanconfig. In most of them we write "{}". But in one case we were writing "\n" intot the .watchmanconfig.

I assume that there's been a new release of watchman which is now stricter about enforcing that .watchmanconfig is well-formed JSON.

Hence this diff, to make us write "{}" in that one case.

Reviewed By: arxanas

Differential Revision: D15530141

fbshipit-source-id: 14ae28fd4b31364a7275bf10a55cbb837544fb59