always define FOLLY_HAVE_PTHREAD and FOLLY_HAVE_CLOCK_GETTIME
Summary:
When building for Windows with `-Wundef` set, we can hit compiler errors with folly includes such as:
```
In file included from .\xplat\folly/Singleton.h:147:
In file included from .\xplat\folly/concurrency/memory/ReadMostlySharedPtr.h:22:
In file included from .\xplat\folly/concurrency/memory/TLRefCount.h:19:
In file included from .\xplat\folly/ThreadLocal.h:60:
In file included from .\xplat\folly/detail/ThreadLocalDetail.h:45:
.\xplat\folly/portability/PThread.h(29,8): error: 'FOLLY_HAVE_PTHREAD' is not defined, evaluates to 0 [-Werror,-Wundef]
   29 | #elif !FOLLY_HAVE_PTHREAD
      |        ^
1 error generated.
```
Instead of leaving the macros undefined, define them to 0 when targeting Win32.

Reviewed By: yfeldblum

Differential Revision: D90265824

fbshipit-source-id: 510fc3e0ed051b7ffd02e8f031e396b133806786