Update Moka crate to 0.9.3
Summary:
Updating the Moka crate to 0.9.3 (latest) to use the iteration functionality.

Changes:
- Updated Moka from 0.8.0 to 0.9.3
- Added `cargo_env = true` fixup to `crossbeam-epoch` since the following error was being thrown while vendoring the updated packages.
```
[2022-08-25T13:29:23.880-07:00] Stderr: error: environment variable `CARGO_PKG_NAME` not defined
  --> third-party/rust/vendor/crossbeam-epoch-0.9.10/build.rs:25:17
   |
25 |                   env!("CARGO_PKG_NAME"),
   |                   ^^^^^^^^^^^^^^^^^^^^^^ in this macro invocation

error: environment variable `CARGO_PKG_NAME` not defined
  --> third-party/rust/vendor/crossbeam-epoch-0.9.10/build.rs:37:17
   |
37 |                   env!("CARGO_PKG_NAME"),
   |                   ^^^^^^^^^^^^^^^^^^^^^^ in this macro invocation
```

Reviewed By: zertosh

Differential Revision: D39035976

fbshipit-source-id: 56d48ac3d845b959c33af579439a41a7d36d7eaf