'plain' error format
Summary:
This is the format you get with `--error-format plain`. It's used for test outputs, so many test outputs are changed.

With the introduction of hack warnings, we need to differentiate between errors and warnings in the outputs.

So far, errors with that format looked like:
```
File "function_return_2.bad.php", line 18, characters 10-13:
Invalid return type (Typing[4110])
  File "function_return_2.bad.php", line 17, characters 19-19:
  Expected `G`
  File "function_return_2.bad.php", line 4, characters 16-18:
  But got `int`
```
With this diff, if the error has severity 'error', it will be printed as:
```
ERROR: File "function_return_2.bad.php", line 18, characters 10-13:
Invalid return type (Typing[4110])
  File "function_return_2.bad.php", line 17, characters 19-19:
  Expected `G`
  File "function_return_2.bad.php", line 4, characters 16-18:
  But got `int`
```
If it has severity warning, it will be printed like:
```
WARN: File "function_return_2.bad.php", line 18, characters 10-13:
Invalid return type (Typing[4110])
  File "function_return_2.bad.php", line 17, characters 19-19:
  Expected `G`
  File "function_return_2.bad.php", line 4, characters 16-18:
  But got `int`
```

Reviewed By: francesco-zappa-nardelli

Differential Revision: D56301941

fbshipit-source-id: 269fd682bddaf2712b7faa3addf35c43bf5e174e