Back out "Patch of Patch example"
Summary:
The way we allow referring to synthesized entities in the same IDL is extremely problematic both for users and for implementers. I think we should look into the design of type resolution (will write a doc) but for now let's say that it is not supported and not advertise workarounds.

This also fixes a compile error caused by interaction with additional type resolution checks:

```
buck build thrift/test:patch_of_patch_test
...thrift/lib/cpp2/op/Get.h:241:1
2: error: no matching function for call to object of type 'const detail::Get<integral_constant<FieldId, 1>, Ba
rEnsureStruct>'
    return op::get<Id, folly::remove_cvref_t<U>>(std::forward<U>(obj));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
b
```

Original commit changeset: ce51bfe6b2df

Original Phabricator Diff: D45972490

Reviewed By: Mizuchi

Differential Revision: D46090598

fbshipit-source-id: d3075769b8595d789ea6e9e18c593f873ecdb455