Address missing ClientStreamInterceptorContext.cpp in cmake
Summary:
D91191164 introduced the new ClientStreamInterceptorContext.cpp but forgot to add it to cmake, which broke FBOSS OSS build
```
undefined reference to `apache::thrift::ClientStreamInterceptorContext::fromContextStack(apache::thrift::ContextStack&)'
```

Reviewed By: vitaut

Differential Revision: D93291714

fbshipit-source-id: c1bef55977f1a338e52a3313e12fbbb2f616f684