Fix regex in run.php for double-digit --count args
Summary:
The original/'fixed' version of this regex put the `\d+` inside a character class, so the `+` never worked correctly for double-digit counts, resulting in errors like this.

```
> hphp/test/run --retranslate-all 5

Fatal error: Uncaught exception 'HH\InvariantException' with message 'unexpected output from shell_exec in runif_test_for_feature: 'Notice: File could not be loaded: 0'' in /data/users/wkl/fbsource/fbcode/hphp/test/run.php:2133
Stack trace:
#0 /data/users/wkl/fbsource/fbcode/hphp/test/run.php(2133): HH\invariant_violation()
#1 /data/users/wkl/fbsource/fbcode/hphp/test/run.php(2189): runif_test_for_feature()
#2 /data/users/wkl/fbsource/fbcode/hphp/test/run.php(2326): runif_function_matches()
#3 /data/users/wkl/fbsource/fbcode/hphp/test/run.php(2965): runif_should_skip_test()
#4 /data/users/wkl/fbsource/fbcode/hphp/test/run.php(2935): run_test()
#5 /data/users/wkl/fbsource/fbcode/hphp/test/run.php(1988): run_and_log_test()
#6 /data/users/wkl/fbsource/fbcode/hphp/test/run.php(3770): child_main()
#7 /data/users/wkl/fbsource/fbcode/hphp/test/run.php(3897): main()
#8 (): run_main()
#9 {main}
```

how_to_regex_garabatokid

Reviewed By: ottoni, mofarrell

Differential Revision: D28401997

fbshipit-source-id: 54dff6a21612cdeea53ddc31e99f4e41fd8205c9