Improve reporting of HackC unit compilation errors (#9648)
Summary:
hackc_compile() calls into Rust via hackc::compile_unit_from_text(). This may return a Rust error that cxxbridge then throws as a C++ exception extending `std::exception`, causing cryptic errors.

For example, after D80369513 /
https://github.com/facebook/hhvm/commit/587ab585dd0d9073b5c583aac3ba80be959dd0d0, trying to run the below Hack file:
```hack
<<__EntryPoint>>
function foo(): void {
	$bar = Silvochka_get_contents('foo.txt');
}
```
returns in an error like:
```
(non-standard exception "N4rust10cxxbridge15ErrorE" was thrown)
```

So, catch and return exceptions during unit compilation. This produces a more friendly error for the above file:
```
Fatal error: Unhandled Emitter error: Unrecoverable: Unexpected Silence operator '@' in /home/mszabo/at.hack on line -1
```

Pull Request resolved: https://github.com/facebook/hhvm/pull/9648

Reviewed By: ricklavoie

Differential Revision: D84202009

fbshipit-source-id: 662a15c061f28a4c205ffca88ea27d59c6d43024