getClass throw on class not found - including classname in error
Summary:
This fixes the lack of context coming from these exceptions, on what the classname might be.

```
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Unable to find class.' in /var/releases/continuous_www_scripts3/flib/intern/build_vault/producers/WWWBuildVaultSandboxCacheProducer.php:126
Stack trace:
#0 /var/releases/continuous_www_scripts3/flib/intern/build_vault/producers/WWWBuildVaultSandboxCacheProducer.php(126): __SystemLib\reflection_class_is_final()
```

By throwing from getClass, we have the context about the union type and can therefore attempt to provide the name in the error.

Reviewed By: ricklavoie

Differential Revision:
D54203472

Privacy Context Container: L1153010

fbshipit-source-id: 887aac97027ebfdd6213354b4227945390253fb6