Add missing "#include <algorithm>" for std::find_if
Summary:
`thrift/lib/cpp2/server/DecoratorDataRuntime.h` uses `std::find_if` but `algorithm` isn't included.

This causes the following error with g++ 14.3.0:

    FAILED: thrift/lib/cpp2/CMakeFiles/thriftcpp2.dir/server/DecoratorDataRuntime.cpp.o ...
    In file included from thrift/lib/cpp2/server/DecoratorDataRuntime.cpp:17:
    thrift/lib/cpp2/server/DecoratorDataRuntime.h: In member function 'apache::thrift::server::DecoratorDataHandle<T> apache::thrift::server::DecoratorDataHandleFactory::makeHandleForKey(const apache::thrift::server::DecoratorDataKey<T>&)':
    thrift/lib/cpp2/server/DecoratorDataRuntime.h:32:24: error: 'find_if' is not a member of 'std'; did you mean 'find'?
       32 |     if (auto it = std::find_if(
          |                        ^~~~~~~
          |                        find

X-link: https://github.com/facebook/fbthrift/pull/669

Reviewed By: sadroeck

Differential Revision: D81513836

Pulled By: iahs

fbshipit-source-id: acf3b1d2a09660fd5fa78fe6f6cea5329acc09ed