Don't put the type name in parenthesis when initializing things in the parser
Because, as the RTM version of MSVC 2015 says, "error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax".

The RC version is actually worse:
```
error C2059: syntax error: '{'
error C2143: syntax error: missing ';' before '{'
error C2143: syntax error: missing ';' before '}'
```

This changes them to normal initializers,