Update rustc to 1.63.0 (2022-08-11) (#9167)
Summary:
Pull Request resolved: https://github.com/facebook/hhvm/pull/9167

This is needed to get D39035976 to pass - the updated version of crossbeam-epoch needs a newer version of rustc.

```
$ wget `fwdproxy-config wget` https://static.rust-lang.org/dist/2022-08-11/rust-nightly-x86_64-apple-darwin.tar.gz
Length: 316593160 (302M) [application/x-tar]

$ wget `fwdproxy-config wget` https://static.rust-lang.org/dist/2022-08-11/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
Length: 287820293 (274M) [application/x-tar]

$ openssl dgst -sha512 *
SHA512(rust-nightly-x86_64-apple-darwin.tar.gz)= 77beb1d67233d3954c2709a47c2513762e91e506041bb5ad8d0aad90124cb5a229dfc87e1fb767826f27a31b52520f148c52c2f3a595dac6e09a676c6e660462
SHA512(rust-nightly-x86_64-unknown-linux-gnu.tar.gz)= de136959121b4117ab31a9ae4c4b3c593d4fcdf9724bd0f62e8a4ab41becccfa4b8e92ebe1460d9be508986888b95b38620bb68b58496db89706760074b9585d

$ for file in *; do manifold put $file hhvm_opensource_dependency_cache/flat/rustc-2022-08-11-$file; done
```

Updated the hhvm.nix hash by updating the date, exporting to github and looking in the failure log for:
```
error: hash mismatch in fixed-output derivation '/nix/store/6jiq2dwm6jl62l3nyhpzy8xb4gxbmnji-channel-rust-nightly.toml.drv':
         specified: sha256-Ur3h+lgPED3 (https://github.com/facebook/hhvm/commit/280e6899b442796a197b5b236d3ddd50d0b62b5f)iDlsLz/M+nP6Wxa5/tmi1DoZpL/IaUkc=
            got:    sha256-wVnIzrnpYGqiCBtc3k55tw4VW8YLA3WZY0mSac+2yl0=
```

Reviewed By: Atry, dtolnay

Differential Revision: D39148189

fbshipit-source-id: a73cab6cf26f70a3d9731fad24a8c3bdbdf9fba7