update version_check-0.9.2 to version_check-0.9.4
Summary:
Fixes:

  error[E0425]: cannot find function `supports_feature` in crate `rustc`
   --> /Users/asuarez/fbsource/third-party/rust/vendor/smartstring-1.0.1/./build.rs:9:44
    |
  9 |     let has_feature = Some(true) == rustc::supports_feature("allocator_api");
    |                                            ^^^^^^^^^^^^^^^^ not found in `rustc`

  For more information about this error, try `rustc --explain E0425`.
  error: could not compile `smartstring` due to previous error

`smartstring` specifies `version_check = "0.9"` in its
`build-dependencies` but `version_check`'s `supports_feature` was added
in v0.9.4.

This version incompatiblity is a problem for building with cargo with a
`crates-io.replace-with` pointing to `third-party/rust`, since they
don't have the hardcoded `smartstring`'s fixup that sidesteps the build
script.

Reviewed By: dtolnay

Differential Revision: D40509231

fbshipit-source-id: e54ce5f4c090816eb244f3c045bbb591ce571c5a