fix violation of warning unused-function under gcc
Summary:
Looks like gcc with `-Werror=unused-function`.

Works around this warning violation:
```
folly/Demangle.cpp:71:35: error: 'void {anonymous}::rust_demangle_callback({anonymous}::poison)' declared 'static' but never defined [-Werror=unused-function]
   71 | [[maybe_unused]] FOLLY_ERASE void rust_demangle_callback(poison);
      |                                   ^~~~~~~~~~~~~~~~~~~~~~
```

Differential Revision: D84838143

fbshipit-source-id: 60b95babdc6c7ea7d71922527727ada927c8fc03