Updated FindTBB for TBB 2021.1
Summary:
TBB 2021.1 broke backwards compatibility (see [release notes](https://www.intel.com/content/www/us/en/developer/articles/release-notes/intel-oneapi-threading-building-blocks-release-notes.html)).

We were looking for `tbb/task_scheduler_init.h` to detect the TBB directory, but this file no longer exists. We also extracted the version from `tbb/tbb_stddef.h` and this file no longer contains the version number. As a result, building on Ubuntu 22.10 failed with:

```
ERROR: Unable to find Intel TBB install directory.
CMake Error at CMake/HPHPFindLibs.cmake:189 (if):
  if given arguments:

    "LESS" "5005"

  Unknown arguments specified
```

Update FindTBB.cmake to try paths from both older TBB versions and TBB 2021.1.

Reviewed By: Atry, alexeyt

Differential Revision: D38727719

fbshipit-source-id: 6a08b246a1309579520a065b93c36456de2d48ea