Add path to LLDB on TW containers, remove unneeded pretty printer test, run unit tests as bundle
Summary:
Three things:
1) Remove an unneeded LLDB pretty printer test (no need to launch HHVM for that single test that's already covered by others)
2) Enable the LLDB unit tests to find lldb on TW containers, so these can hopefully start passing in Sandcastle ([comment in Native Debugging](https://fb.workplace.com/groups/native.debugging/posts/1880681062315732/?comment_id=1881013885615783&reply_comment_id=1883022448748260))
3) Run these [as_bundle](https://www.internalfb.com/intern/wiki/TAE/TestPilot/TestPilot/changing-test-behavior/#run-as-bundle); without it, you see errors like:
```
======================================================================
FAIL: test_sizeof_helper_indexed_string_map (hphp.tools.lldb.test.test_sizeof.IdxCommandTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/michristensen/fbsource/buck-out/v2/gen/fbcode/3d16628cbe241676/hphp/tools/lldb/__lldb_tests__/lldb_tests#link-tree/hphp/tools/lldb/test/test_sizeof.py", line 9, in setUp
    super().setUp(test_file="quick/properties2.php", interp=True)
  File "/data/users/michristensen/fbsource/buck-out/v2/gen/fbcode/3d16628cbe241676/hphp/tools/lldb/__lldb_tests__/lldb_tests#link-tree/hphp/tools/lldb/test/base.py", line 112, in setUp
    super().setUp()
  File "/data/users/michristensen/fbsource/buck-out/v2/gen/fbcode/3d16628cbe241676/hphp/tools/lldb/__lldb_tests__/lldb_tests#link-tree/hphp/tools/lldb/test/base.py", line 44, in setUp
    assert process.IsValid() and error.Success(), f"Unable to launch process ({get_lldb_object_description(error)})"
AssertionError: Unable to launch process (error: failed to get reply to handshake packet within timeout of 6.0 seconds)
```
for about half the tests, even though they all currently pass when run individually.

Reviewed By: jtwarren

Differential Revision: D46610079

fbshipit-source-id: b44f9f9b313a97093964dd2309a4727b33b22eac