Fix OSS build - Remove extra OR operator
Summary: D1627415 introduced an extra `|` operator that the OSS compiler does not like:

```
/tmp/hhvm_oss_sync_and_push/hhvm/hphp/runtime/base/object-data.cpp: In member function ‘void HPHP::ObjectData::getProp(const HPHP::Class*, bool, const HPHP::PreClass::Prop*, HPHP::Array&, std::vector<bool>&) const’:
/tmp/hhvm_oss_sync_and_push/hhvm/hphp/runtime/base/object-data.cpp:1721:9: error: expected primary-expression before ‘|’ token
         | AttrBuiltin // runtime-internal attrs, such as the <<Memoize>> cache
```

Reviewed By: @ptarjan, @paulbiss

Differential Revision: D1628431