Fix an incomplete type error in dynamic patch
Summary:
Using `DynamicPatch` before it is defined in `F14VectorMap` is non-portable. Fix it by moving the definition before usage.

Fixes:

```
In file included from fbcode/cathode/experimental/duplex_bot_module/MessagePublisher.cpp:3:
In file included from buck-out/v2/gen/fbcode/b8b24153b7c1abba/cathode/experimental/duplex_bot_module/__message_publisher__/buck-headers/cathode/experimental/duplex_bot_module/MessagePublisher.h:3:
In file included from buck-out/v2/gen/fbcode/b8b24153b7c1abba/folly/__executor__/buck-headers/folly/Executor.h:21:
In file included from fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/utility:70:
fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/stl_pair.h:218:11: error: field has incomplete type 'apache::thrift::protocol::DynamicPatch'
  218 |       _T2 second;                ///< The second member
      |           ^
fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/ext/aligned_buffer.h:91:28: note: in instantiation of template class 'std::pair<const apache::thrift::protocol::detail::ValueWrapper<>, apache::thrift::protocol::DynamicPatch>' requested here
   91 |     : std::aligned_storage<sizeof(_Tp), __alignof__(_Tp)>
      |                            ^
fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/hashtable_policy.h:235:43: note: in instantiation of template class '__gnu_cxx::__aligned_buffer<std::pair<const apache::thrift::protocol::detail::ValueWrapper<>, apache::thrift::protocol::DynamicPatch>>' requested here
  235 |       __gnu_cxx::__aligned_buffer<_Value> _M_storage;
      |                                           ^
fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/hashtable_policy.h:270:7: note: in instantiation of template class 'std::__detail::_Hash_node_value_base<std::pair<const apache::thrift::protocol::detail::ValueWrapper<>, apache::thrift::protocol::DynamicPatch>>' requested here
  270 |     : _Hash_node_value_base<_Value>
      |       ^
fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/hashtable_policy.h:280:7: note: in instantiation of template class 'std::__detail::_Hash_node_value<std::pair<const apache::thrift::protocol::detail::ValueWrapper<>, apache::thrift::protocol::DynamicPatch>, false>' requested here
  280 |     , _Hash_node_value<_Value, _Cache_hash_code>
      |       ^
fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/hashtable_policy.h:1812:25: note: in instantiation of template class 'std::__detail::_Hash_node<std::pair<const apache::thrift::protocol::detail::ValueWrapper<>, apache::thrift::protocol::DynamicPatch>, false>' requested here
 1812 |         rebind_traits<typename __node_type::value_type>;
      |                                ^
fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/hashtable_policy.h:812:42: note: (skipping 2 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
  812 |       using __node_alloc_type = typename __hashtable_alloc::__node_alloc_type;
      |                                          ^
fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/hashtable.h:176:14: note: in instantiation of template class 'std::__detail::_Insert<apache::thrift::protocol::detail::ValueWrapper<>, std::pair<const apache::thrift::protocol::detail::ValueWrapper<>, apache::thrift::protocol::DynamicPatch>, std::allocator<std::pair<const apache::thrift::protocol::detail::ValueWrapper<>, apache::thrift::protocol::DynamicPatch>>, std::__detail::_Select1st, folly::HeterogeneousAccessEqualTo<apache::thrift::protocol::detail::ValueWrapper<>>, folly::HeterogeneousAccessHash<apache::thrift::protocol::detail::ValueWrapper<>>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>>' requested here
  176 |       public __detail::_Insert<_Key, _Value, _Alloc, _ExtractKey, _Equal,
      |              ^
fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/unordered_map.h:105:18: note: in instantiation of template class 'std::_Hashtable<apache::thrift::protocol::detail::ValueWrapper<>, std::pair<const apache::thrift::protocol::detail::ValueWrapper<>, apache::thrift::protocol::DynamicPatch>, std::allocator<std::pair<const apache::thrift::protocol::detail::ValueWrapper<>, apache::thrift::protocol::DynamicPatch>>, std::__detail::_Select1st, folly::HeterogeneousAccessEqualTo<apache::thrift::protocol::detail::ValueWrapper<>>, folly::HeterogeneousAccessHash<apache::thrift::protocol::detail::ValueWrapper<>>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>>' requested here
  105 |       _Hashtable _M_h;
      |                  ^
buck-out/v2/gen/fbcode/b8b24153b7c1abba/folly/container/detail/__f14_hash_detail__/buck-headers/folly/container/detail/F14MapFallback.h:42:28: note: in instantiation of template class 'std::unordered_map<apache::thrift::protocol::detail::ValueWrapper<>, apache::thrift::protocol::DynamicPatch, folly::HeterogeneousAccessHash<apache::thrift::protocol::detail::ValueWrapper<>>, folly::HeterogeneousAccessEqualTo<apache::thrift::protocol::detail::ValueWrapper<>>>' requested here
   42 | class F14BasicMap : public std::unordered_map<K, M, H, E, A> {
      |                            ^
buck-out/v2/gen/fbcode/b8b24153b7c1abba/folly/container/detail/__f14_hash_detail__/buck-headers/folly/container/detail/F14MapFallback.h:675:14: note: in instantiation of template class 'folly::f14::detail::F14BasicMap<apache::thrift::protocol::detail::ValueWrapper<>, apache::thrift::protocol::DynamicPatch, folly::HeterogeneousAccessHash<apache::thrift::protocol::detail::ValueWrapper<>>, folly::HeterogeneousAccessEqualTo<apache::thrift::protocol::detail::ValueWrapper<>>, std::allocator<std::pair<const apache::thrift::protocol::detail::ValueWrapper<>, apache::thrift::protocol::DynamicPatch>>>' requested here
  675 |     : public f14::detail::F14BasicMap<Key, Mapped, Hasher, KeyEqual, Alloc> {
      |              ^
buck-out/v2/gen/fbcode/b8b24153b7c1abba/thrift/lib/thrift/__any-patch-cpp2-types__/buck-headers/thrift/lib/thrift/detail/DynamicPatch.h:571:44: note: in instantiation of template class 'folly::F14VectorMap<apache::thrift::protocol::detail::ValueWrapper<>, apache::thrift::protocol::DynamicPatch>' requested here
  571 |   folly::F14VectorMap<Value, DynamicPatch> patchPrior_;
      |                                            ^
buck-out/v2/gen/fbcode/b8b24153b7c1abba/thrift/lib/thrift/__any-patch-cpp2-types__/buck-headers/thrift/lib/thrift/detail/DynamicPatch.h:105:7: note: forward declaration of 'apache::thrift::protocol::DynamicPatch'
  105 | class DynamicPatch;
      |       ^
```

Reviewed By: sadroeck

Differential Revision: D74936918

fbshipit-source-id: 35d5caca30f4894e65808aec0b516ffdbe317928