Revert "Update Kohana framework to v3.3.4"
Summary: This reverts commit de45a33a782aba3596e8d5f4e8cbd44b75640b0b.

```
  ERROR: Could not get tests for kohana
```

refs facebook/hhvm#5568

Reviewed By: @JoelMarcey

Differential Revision: D2277621