Actually make AsyncMysqlQueryResult implement clientStats
Summary: We have a bug in `ext_async_mysql.cpp` where we had `clientStats` implemented twice by the same class,
and not by a class that actually requires. So, we would get something like:

```
hhvmb clientStats.php

Fatal error: Call to unimplemented native method AsyncMysqlQueryResult::clientStats() in user-documentation/guides/hack/99-api-examples/async-mysql-examples/async-mysql-query-result-examples/clientStats.php on line 23
```

Fix that bug.

Reviewed By: @fredemmott

Differential Revision: D2465029