Fix error recovery for darray and varray types in ffp
Summary:
This was causing `return (darray[])` to error because of the way we speculatively
parse lambdas.

Parsing the following simple repro:

```
<?hh
// Copyright 2004-present Facebook. All Rights Reserved.

class X {
  function Y() {
    return (darray[]);
  }
}
```

Generated this error:

```
Fatal error: exception Failure("Expected token < but got [\n")
Raised at file "pervasives.ml", line 32, characters 22-33
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_parser_helpers.ml", line 305, characters 6-148
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_type_parser.ml", line 341, characters 29-57
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_declaration_parser.ml", line 36, characters 30-62
Called from unknown location
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_parser_helpers.ml", line 376, characters 29-46
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_parser_helpers.ml", line 400, characters 26-39
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_parser_helpers.ml", line 460, characters 26-44
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_expression_parser.ml", line 69, characters 6-53
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_expression_parser.ml", line 1273, characters 42-73
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_expression_parser.ml", line 1245, characters 32-61
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_expression_parser.ml", line 110, characters 27-35
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_expression_parser.ml", line 950, characters 12-39
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_expression_parser.ml", line 86, characters 25-42
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_statement_parser.ml", line 771, characters 36-55
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_statement_parser.ml", line 575, characters 27-50
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_parser_helpers.ml", line 535, characters 31-48
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_parser_helpers.ml", line 537, characters 26-39
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_statement_parser.ml", line 756, characters 8-63
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_declaration_parser.ml", line 74, characters 35-84
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_declaration_parser.ml", line 1357, characters 27-58
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_parser_helpers.ml", line 535, characters 31-48
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_parser_helpers.ml", line 537, characters 26-39
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_declaration_parser.ml", line 451, characters 6-44
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_declaration_parser.ml", line 354, characters 25-51
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_declaration_parser.ml", line 1473, characters 34-58
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_declaration_parser.ml", line 1487, characters 33-46
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_parser.ml", line 51, characters 28-63
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_syntax_tree.ml", line 105, characters 23-49
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/parser/full_fidelity_ast.ml", line 2111, characters 17-33
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/hh_single_parse.ml", line 141, characters 42-56
Called from file "unix.ml", line 173, characters 4-9
Re-raised at file "unix.ml", line 96, characters 4-2598
Called from file "/data/users/paulbiss/fbsource/fbcode/hphp/hack/src/hh_single_parse.ml", line 293, characters 2-147
```

Reviewed By: oulgen, vladima

Differential Revision: D5409983

fbshipit-source-id: c86ae3593a7aa8548dfcf99d6df6d462ebad4e97