better error message if sqlite doesn't exist
Summary:
We sometimes see the error message
```
Fatal error: exception Sqlite3.Error("Sqlite3.prepare: no such table: NAMING_LOCAL_CHANGES")
```
e.g. https://internalfb.com/intern/sandcastle/job/971782555/artifact/actionlog.11063954726.log?selectedLines=1533-1534-1-1

The underlying problem is that the sqlite file doesn't exist... sqlite will happily open a non-existing file, which "touches" it (causing it to be created with zero size), and deems it to have no tables in it. Hence "no such table" for the first table we try to open.

This diff changes it to a more informative error.

Reviewed By: bobrenjc93

Differential Revision: D46630631

fbshipit-source-id: 0390dd6449756799cc97309c78e548378615f038