Fix logging-profile.h under GCC 9
Summary:
Static initializer of `std::atomic<SinkLayout>` fails as
construction must be noexcept. Given it works in both older and
newer GCCs, and it appears that the problems are due to
`jit::ArrayLayout` - which was previously used directly without
problems - I think this is a GCC9 quirk more than anything else.

Isolated repro:

```
#include <atomic>
class Foo {
  public:
    Foo() {
    }
};

std::atomic<Foo> g_foo = {};
```

```
$ g++ -std=c++17 -c test.cpp
test.cpp:8:27: error: use of deleted function 'std::atomic<_Tp>::atomic() [with _Tp = Foo]'
    8 | std::atomic<Foo> g_foo = {};
      |                           ^
In file included from test.cpp:1:
/usr/include/c++/9/atomic:198:7: note: 'std::atomic<_Tp>::atomic() noexcept [with _Tp = Foo]' is implicitly deleted because its exception-specification does not match the implicit exception-specification ''
  198 |       atomic() noexcept = default;
      |       ^~~~~~
```

Differential Revision: D28384462

fbshipit-source-id: 1e4c7b08253e917eb8e255cd304f381eef2116c6