Fix default trivially construct-able problems in C++20
Summary:
In C++20, std::atomic is no longer trivially constructable
```
hphp/runtime/base/memory-manager.h:457:12: error: call to implicitly-deleted default constructor of 'HPHP::HeapObject'
  explicit MemoNode(uint32_t objoff) {
           ^
hphp/runtime/base/header-kind.h:166:63: note: default constructor of 'HeapObject' is implicitly deleted because variant field 'm_atomic_count' has a non-trivial default constructor
    mutable std::atomic<std::underlying_type<RefCount>::type> m_atomic_count;
```

Reviewed By: ottoni

Differential Revision: D33945294

fbshipit-source-id: 4ae51564f90577c57c10bb145924791037309128