thrift: Fix FBLite compilation errors
Summary:
Some lambdas were failing to compile when building fblite because capture this via = is deprecated. This diff explicitly captures this in these diffs.

Example error messages:
```
fbcode/thrift/lib/cpp2/async/AsyncProcessor.cpp:234:39: error: implicit capture of 'this' with a capture default of '=' is deprecated [-Werror,-Wdeprecated-this-capture]
  234 |             auto tilePtr = nullthrows(createInteractionImpl(
      |                                       ^
fbcode/thrift/lib/cpp2/async/AsyncProcessor.cpp:231:10: note: add an explicit capture of 'this' to capture '*this' by reference
  231 |         [=, &eb, &conn] {
      |          ^
      |           , this
fbcode/thrift/lib/cpp2/async/AsyncProcessor.cpp:315:35: error: implicit capture of 'this' with a capture default of '=' is deprecated [-Werror,-Wdeprecated-this-capture]
  315 |         auto tilePtr = nullthrows(createInteractionImpl(name));
      |                                   ^
fbcode/thrift/lib/cpp2/async/AsyncProcessor.cpp:308:14: note: add an explicit capture of 'this' to capture '*this' by reference
  308 |     tm->add([=, &eb, &ctx, name = std::move(name), &conn] {
      |              ^
      |               , this
```

Reviewed By: ChristianK275, KyleFung

Differential Revision: D65887785

fbshipit-source-id: 2c3686e73c807192b48512de4567939d20fc0294