add new Hack server command to concatenate all files in a directory (#8598)
Summary:
- removes headers
- converts `namespace Foo;` to `namespace Foo {}`
- resolves inclusion order; this is needed for class deps to avoid
  runtime errors - parents can be declared later in the file, but this
  is non-recursive, so grandparents must be declared first

This is intended for:
 - generating a single-file version of the HSL suitable for embedding
 - potential make_systemlib.sh replacement
 - potential phar replacement

HSL/SystemLib embedding are why this is being added to `hh_server`,
instead of using HackAST/HHAST

Pull Request resolved: https://github.com/facebook/hhvm/pull/8598

Test Plan:
```
$ cd code/hsl
$ hh_client --concatenate-all $(pwd)/src > hsl.hack
$ hhvm hsl.hack # no output - no entrypoints or errors
$ hhvm --php -r 'var_dump(HH\facts_parse("", varray["./hsl.hack"], false, true));' | pbpaste

Output pastebin at https://gist.github.com/fredemmott/d8bc4b3f1f12b7a112faa49383ee1878

$ cd /tmp/hhtest
$ cat *.hack > ../dumb.hack
$ cat ../dumb.hack
class Herp {}
class Baz extends Bar {}
class Bar extends Foo {}
class Foo {}
class Qux extends Bar {}
$ hhvm ../dumb.hack

Fatal error: Uncaught Error: unknown class Bar in /private/tmp/dumb.hack:2
Stack trace:
 #0 {main}
$ hh_client --concatenate-all "" > ../smart.hack
$ hhvm ../smart.hack # no output - no entrypoints or errors
$ cat ../smart.hack
///// 3-grandparent.hack /////
class Foo {}

///// 2-parent.hack /////
class Bar extends Foo {}

///// 5-sibling.hack /////
class Qux extends Bar {}

///// 1-child.hack /////
class Baz extends Bar {}

///// 0-unrelated.hack /////
class Herp {}
```

Reviewed By: ljw1004

Differential Revision: D18480086

fbshipit-source-id: f5149e67d077bd8189a1928a9828412739e9d5a2