Fix OSS Build due to tuple changes
Summary: D1305592 did some good things for tuples. Unfortunately, the OSS build breaks with it. It won't compile.

Scanning dependencies of target hphp_parser
[ 24%] Building CXX object hphp/parser/CMakeFiles/hphp_parser.dir/lex.yy.cpp.o
hphp/parser/hphp.ll: In function ‘int hphplex(HPHP::ScannerToken*, HPHP::Location*, yyscan_t)’:
hphp/parser/hphp.ll:466:3: error: ‘T_TUPLE’ was not declared in this scope
make[2]: *** [hphp/parser/CMakeFiles/hphp_parser.dir/lex.yy.cpp.o] Error 1
make[1]: *** [hphp/parser/CMakeFiles/hphp_parser.dir/all] Error 2
make: *** [all] Error 2

I thought lex.yy.cpp would get automatically regenerated during the make process, but it doesn't. In fact, make-parser.sh doesn't even touch the file.

Reviewed By: @jdelong

Differential Revision: D1313253