Update rand from 0.8.5 to 0.8.6
Summary:
Fixes https://rustsec.org/advisories/RUSTSEC-2026-0097.html

This requires disabling tvOS support on a bunch of crates that depend on old `rand`.

```lang=log,counterexample
Action failed: fbsource//third-party/rust/vendor/getrandom:0.1 (rustc check)
error: target is not supported, for more information see: https://docs.rs/getrandom/#unsupported-targets
   --> third-party/rust/vendor/getrandom-0.1.15/src/lib.rs:257:9
    |
257 | /         compile_error!("\
258 | |             target is not supported, for more information see: \
259 | |             https://docs.rs/getrandom/#unsupported-targets\
260 | |         ");
    | |__________^

BUILD FAILED
Failed to build 'fbsource//third-party/rust/vendor/getrandom:0.1 (ovr_config//platform/appletvos:arm64-fbsource#ed7750f8d71e46ab)'
Failed to build 'fbsource//third-party/rust/vendor/getrandom:0.1 (ovr_config//platform/appletvos:arm64-simulator-fbsource#345c84a5a5155881)'
```

Reviewed By: diliop

Differential Revision: D104350816

fbshipit-source-id: 7ac8cd35e79c51a8478503e49f2b85e078ab4d5c