Fix thrift OSS errors
Summary:
There were some changes breaking OSS builds introduced in D92333678 and D91532159.

```
/opt/rh/gcc-toolset-12/root/usr/libexec/gcc/x86_64-redhat-linux/12/ld: /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/lib/libthriftcpp2.a(Cpp2Worker.cpp.o): in function `apache::thrift::ThriftParametersServerExtension::getExtensions(fizz::ClientHello const&)':
Cpp2Worker.cpp:(.text._ZN6apache6thrift31ThriftParametersServerExtension13getExtensionsERKN4fizz11ClientHelloE[_ZN6apache6thrift31ThriftParametersServerExtension13getExtensionsERKN4fizz11ClientHelloE]+0xdd): undefined reference to `apache::thrift::ThriftParametersServerExtension::negotiate(apache::thrift::ThriftParametersExt const&, apache::thrift::ThriftParametersContext const&)'
/opt/rh/gcc-toolset-12/root/usr/libexec/gcc/x86_64-redhat-linux/12/ld: /data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/lib/libthrift_dynamic_value.a(Any.cpp.o): in function `apache::thrift::dynamic::Any apache::thrift::dynamic::deserialize<apache::thrift::SimpleJSONProtocolReader>(apache::thrift::SimpleJSONProtocolReader&, apache::thrift::type_system::detail::PrimitiveTypeIdWrapper<apache::thrift::type_system::AnyTypeIdStruct>, std::pmr::memory_resource*) [clone .isra.0]':
Any.cpp:(.text+0xe31): undefined reference to `void apache::thrift::type::AnyStruct::readNoXfer<apache::thrift::SimpleJSONProtocolReader>(apache::thrift::SimpleJSONProtocolReader*)'
collect2: error: ld returned 1 exit status
```

Reviewed By: iahs

Differential Revision: D93892028

fbshipit-source-id: d2cb62144cff00faf86f4a08b196e681e181baf1