Use Rust nightly from October 14th, 2024
Although the nightly from October 13th is the last one prior to the
1.83 beta cut, it's missing
https://github.com/rust-lang/rust/pull/131287 which landed in 1.83.0.

This causes HHBC compilation to fail:

```
error: `std::option::Option::<T>::unwrap` is not yet stable as a const fn
   --> hackc/hhbc/cargo/hhbc/../../types.rs:153:17
    |
153 |     let parts = name.as_bytes().split_first().unwrap();
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add `#![feature(const_option)]` to the crate attributes to enable
```

Update to the nightly from the next day instead to pull in this change.