add ServerSinkFactory.cpp to CMakeLists.txt
Summary:
File was added in D89140244 (danieldeng), resulting in failure to build oss fboss:

https://www.internalfb.com/sandcastle/workflow/716072340764645535
```
...
otocolReaderENS0_21CompactProtocolWriterEE11process_exnEPKcNS0_21TApplicationException25TApplicationExceptionTypeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt10unique_ptrINS0_22ResponseChannelRequestENS0_16RequestsRegistry7DeleterEEPNS0_18Cpp2RequestContextEPN5folly9EventBaseEiENUlvE_clEv]+0xb8): undefined reference to `apache::thrift::detail::ServerSinkFactory::ServerSinkFactory()'
collect2: error: ld returned 1 exit status
```

This diff follows the pattern of prior changes to the makefile in D73378222

Reviewed By: aristidisp

Differential Revision: D90171644

fbshipit-source-id: bcf003b2816db4169e46348b3e51a9c150ab5d53