Remove support for non-code ('markup') sections, `<?hh` always optional
First, to clarify the terms

```
This is leading markup
<?php
?>
this is markup, but not leading markup
```

This diff
- removes support for all kinds of markup except for a leading shebang line, in
  all languages
- removes differing leading markup behavior for HHVM mode vs other parser modes
- removes all parser-level differences between `.hack` and other files
- makes `?>` invalid
- makes `<?` optional in non-hack files: if omitted, they will be
  considered strict. `<?` remains banned in `.hack` files.

This diff is because making the parser act differently based on the
filename extension is incredibly brittle, especially when the LSP is
involved. This is also why `<?` is now optional for PHP files.

Reviewers: jjergus, kunalm, rmlynch

Test plan:

- existing unit tests (a bunch are going to break, I'll fix them on FB
infra)
- hh_client and unit tests for HHAST. This covers a bunch of weird caes

```
$ for file in *; do echo ">>>> $file <<<<"; cat $file; done
>>>> header.hack <<<<
<?hh // strict

function header_dot_hack(): void {
}
>>>> header.php <<<<
<?hh // strict

function header_dot_php(): void {}
>>>> no_header.php <<<<
function no_header_dot_php(): void {}
>>>> qmgt.php <<<<
<?php

echo 'foo';

?>
>>>> shebang.hack <<<<
function shebang_dot_hack(): void {}
>>>> shebang.php <<<<
<?hh // strict
>>>> shebang_header.hack <<<<
<?hh // strict
$ hh_client
header.hack:1:1,4: Leading markup and `<?hh` are not permitted in `.hack` files, which are always strict. (Parsing[1002])
shebang_header.hack:1:1,24: Leading markup and `<?hh` are not permitted in `.hack` files, which are always strict. (Parsing[1002])
$ hhvm qmgt.php

Fatal error: Uncaught Error: An expression is expected here. in /private/tmp/hhtest/qmgt.php:6
Stack trace:
```