Update semver-parser from 0.10.1 to 0.10.3
Summary:
As of 1.86.0, Rust is no longer able to build semver-parser 0.10.1 as a result of [**rust-lang/rust#134276**](https://github.com/rust-lang/rust/pull/134276).

```lang=text,counterexample
Action failed: fbsource//third-party/rust:semver-parser-0.10.1 (rustc rlib)
error[E0658]: custom inner attributes are unstable
 --> third-party/rust/vendor/semver-parser-0.10.1/src/generated.rs:4:4
  |
4 | #![rustfmt::skip]
  |    ^^^^^^^^^^^^^
  |
  = note: see issue #54726 <https://github.com/rust-lang/rust/issues/54726> for more information
  = help: add `#![feature(custom_inner_attributes)]` to the crate attributes to enable
  = note: this compiler was built on 2025-03-31; consider upgrading it if it is out of date
```

Differential Revision: D72617069

fbshipit-source-id: 91cd7e54ff9ab1bae6eb733a795a4c23076baa79