Remove is_array_get special case from expression printer
Summary:
Noticed this when adding support for `Nameof` that also carries a `class_id` in one of its variants. We have a strange special case for the expression printer for array access when the index is a `::class` expression:
```
function f(
  dict $i = dict["C" => 4],
  int $j = $i[C::class],
  int $k = C::class,
): void {
  var_dump($j);
}
```
this prints `int(4)` when `f()` is invoked. The bytecode for this definition is
```
.function {} [interceptable] (8,14) <"HH\\void" N > f(
  <"HH\\dict" "HH\\dict" > $i = DV1("""dict[\"C\" => 4]"""),
  <"HH\\int" "HH\\int" > $j = DV2("""$i[C]"""),
  <"HH\\string" "HH\\string" > $k = DV3("""\"C\"""")
) {
```
(formatting mine). Note the unquoted `C` in `DV2("""$i[C]""")` compared to the quoted `C` for `$k = DV3("""\"C\"""")`. The former seems weird and malformed, but it does work at runtime. We're moving toward eliminating KindOf[Lazy]Class coercions to strings so we'd be changing this to a `nameof C` or even just a `"C"` expression anyway. By eliminating the special case, we now emit `$j = DV2("""$i[\"C\"]""")`.

# Runtime difference - prod HHVM

In currently-released HHVM, given
```
function f(
  dict $i = dict["C" => 4],
  int $j = $i[C::class],
  // int $k = $i["C"],
): void {}
```
this Reflection code
```
  $f = new ReflectionFunction("f");
  var_dump($f->getParameters()[1]->getDefaultValueText());
```
prints
```
Warning: Failed to eval default value of f()'s $j argument for reflection, assigning NULL instead in /home/vmladenov/j.php on line 6
string(5) "$i[C]"
```
whereas flipping the comments
```
function f(
  dict $i = dict["C" => 4],
  // int $j = $i[C::class],
  int $k = $i["C"],
): void {}
```
causes
```
Notice: Evaluation of default arg initializer in func=f, arg=k threw a PHP exception--this reflection call won't throw in future HHVMs! in /home/vmladenov/j.php on line 6

Fatal error: Uncaught exception 'UndefinedVariableException' with message 'Undefined variable: i' in :1
```

**This change would make both situations fail like the latter case.** I submit that the former is extremely clowny and both cases should be the same.

> Note: as before, both versions print `int(4)` if `f()` is invoked and the variable is `var_dump`ed. Reflection is what differs.

RFC

Reviewed By: aorenste

Differential Revision: D49213162

fbshipit-source-id: a2545de6dad641a1faaed85279536bd55d4f5cd9