Use `const` in xlog.h
Summary:
We'd like to use `misc-const-correctness` in our codebase. To do so, we need to fix an issue in folly.

As below, that issue turns out to be unfixable do to templates, so instead we disable the const correctness check for this line of

Running
```
arc cast fbsource//xplat/tools/cAST:fbtidy --autofix -checks="-*,misc-const-correctness" --keep-going -paths algopt/common/tests/UtilsTest.cpp
```
causes this error
```
fbcode/algopt/common/tests/UtilsTest.cpp:149:3: error: variable 'folly_detail_xlog_level' of type '::folly::XlogLevelInfo<bool(0 > 0)>' can be declared 'const' [misc-const-correctness,-warnings-as-errors]
  149 |   XLOG(INFO) << sortedWithHeader;
      |   ^
buck-out/v2/gen/fbcode/5c36589227cec5f0/folly/logging/__logging__/buck-headers/folly/logging/xlog.h:88:3: note: expanded from macro 'XLOG'
   88 |   XLOG_IMPL(                               \
      |   ^
buck-out/v2/gen/fbcode/5c36589227cec5f0/folly/logging/__logging__/buck-headers/folly/logging/xlog.h:481:3: note: expanded from macro 'XLOG_IMPL'
  481 |   XLOG_ACTUAL_IMPL(                 \
      |   ^
buck-out/v2/gen/fbcode/5c36589227cec5f0/folly/logging/__logging__/buck-headers/folly/logging/xlog.h:531:5: note: expanded from macro 'XLOG_ACTUAL_IMPL'
  531 |   (!XLOG_IS_ON_IMPL(level) || !(cond))                                      \
      |     ^
buck-out/v2/gen/fbcode/5c36589227cec5f0/folly/logging/__logging__/buck-headers/folly/logging/xlog.h:578:5: note: expanded from macro 'XLOG_IS_ON_IMPL'
  578 |     XLOG_IS_ON_IMPL_HELPER(level)) ||                       \
      |     ^
buck-out/v2/gen/fbcode/5c36589227cec5f0/folly/logging/__logging__/buck-headers/folly/logging/xlog.h:598:5: note: expanded from macro 'XLOG_IS_ON_IMPL_HELPER'
  598 |     static ::folly::XlogLevelInfo<XLOG_IS_IN_HEADER_FILE>       \
      |     ^
```

But if we use `const` as indicated above we see
```
[2025-07-25T09:41:31.003-07:00] Stderr:
 In file included from fbcode/thrift/lib/cpp2/async/RpcTypes.cpp:17:
 In file included from buck-out/v2/gen/fbcode/deaf73848e0e6685/thrift/lib/cpp2/async/__rpc_types__/buck-headers/thrift/lib/cpp2/async/RpcTypes.h:23:
 In file included from buck-out/v2/gen/fbcode/deaf73848e0e6685/thrift/lib/cpp2/transport/rocket/payload/__payload_serializer__/buck-headers/thrift/lib/cpp2/transport/rocket/payload/PayloadSerializer.h:22:
 buck-out/v2/gen/fbcode/deaf73848e0e6685/thrift/lib/cpp2/transport/rocket/payload/__payload_serializer__/buck-headers/thrift/lib/cpp2/transport/rocket/payload/ChecksumPayloadSerializerStrategy.h:262:7: error: 'this' argument to member function 'check' has type 'const ::folly::XlogLevelInfo<bool(3 > 0)>', but function is not marked const
       |       ^~~~~~~~~~~~~~~~~~~~~~~~~
 buck-out/v2/gen/fbcode/deaf73848e0e6685/folly/logging/__logging__/buck-headers/folly/logging/xlog.h:134:3: note: expanded from macro 'XLOG_EVERY_MS'
       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   140 |         return folly_detail_xlog_limiter.check();                     \
       |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       |       ~~~~~~~~~~~~~~
 buck-out/v2/gen/fbcode/deaf73848e0e6685/folly/logging/__logging__/buck-headers/folly/logging/xlog.h:99:3: note: expanded from macro 'XLOG_IF'
       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   100 |       ::folly::LogLevel::level,            \
       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       |       ~~~~~~~~~~~~~~
 buck-out/v2/gen/fbcode/deaf73848e0e6685/folly/logging/__logging__/buck-headers/folly/logging/xlog.h:485:3: note: expanded from macro 'XLOG_IF_IMPL'
       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 buck-out/v2/gen/fbcode/deaf73848e0e6685/folly/logging/__logging__/buck-headers/folly/logging/xlog.h:531:5: note: expanded from macro 'XLOG_ACTUAL_IMPL'
       |     ^~~~~~~~~~~~~~~~~~~~~~
 buck-out/v2/gen/fbcode/deaf73848e0e6685/folly/logging/__logging__/buck-headers/folly/logging/xlog.h:578:5: note: expanded from macro 'XLOG_IS_ON_IMPL'
       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 buck-out/v2/gen/fbcode/deaf73848e0e6685/folly/logging/__logging__/buck-headers/folly/logging/xlog.h:604:12: note: expanded from macro 'XLOG_IS_ON_IMPL_HELPER'
       |            ^~~~~~~~~~~~~~~~~~~~~~~
 buck-out/v2/gen/fbcode/deaf73848e0e6685/folly/logging/__logging__/buck-headers/folly/logging/xlog.h:821:8: note: 'check' declared here
       |        ^
 1 error generated.
```

Differential Revision: D78984373

fbshipit-source-id: 89e6ce0265130c3f54e4cdc3338e5386bf41b7a9