Fix syntax graph build on Windows differently
Summary:
Original error:

```
In file included from buck-out\v2\gen\fbcode\c754018c63893fbf\thrift\lib\cpp2\schema\__syntax_graph_if-cpp2-syntax_graph.thrift__\out\gen-cpp2\syntax_graph_constants.cpp:8:
In file included from buck-out\v2\gen\fbcode\c754018c63893fbf\thrift\lib\cpp2\schema\__syntax_graph_if-cpp2-types__\buck-headers\thrift/lib/cpp2/schema/gen-cpp2/syntax_graph_constants.h:11:
buck-out\v2\gen\fbcode\c754018c63893fbf\thrift\lib\cpp2\schema\__syntax_graph_if-cpp2-types__\buck-headers\thrift/lib/cpp2/schema/gen-cpp2/syntax_graph_types.h:31:12: error: expected identifier
  OPTIONAL = 2,
           ^
buck-out\v2\gen\fbcode\c754018c63893fbf\thrift\lib\cpp2\schema\__syntax_graph_if-cpp2-types__\buck-headers\thrift/lib/cpp2/schema/gen-cpp2/syntax_graph_types.h:96:54: error: expected unqualified-id
  static constexpr type max() { return type::OPTIONAL; }
                                                     ^
buck-out\v2\gen\fbcode\c754018c63893fbf\thrift\lib\cpp2\schema\__syntax_graph_if-cpp2-types__\buck-headers\thrift/lib/cpp2/schema/gen-cpp2/syntax_graph_types.h:96:25: error: no return statement in constexpr function
  static constexpr type max() { return type::OPTIONAL; }
                        ^
```

New error caused by `#undef OPTIONAL`:
```
In file included from third-party\boost\boost\boost\asio\detail\socket_types.hpp:41:
third-party\toolchains\windows10sdk\10.0.22000.0\Include\10.0.22000.0\um\mswsock.h(515,46): error: expected ')'
  515 |     _Inout_opt_ LPWSAOVERLAPPED lpOverlapped OPTIONAL,
      |                                              ^
third-party\toolchains\windows10sdk\10.0.22000.0\Include\10.0.22000.0\um\mswsock.h(510,32): note: to match this '('
  510 | (PASCAL FAR * LPFN_WSASENDMSG) (
      |                                ^
```

Reviewed By: prakashgayasen

Differential Revision: D74015969

fbshipit-source-id: 9f3e7e7a05c93422484ecbb939b72903a52c2348