Back out "make_exception_ptr_with"
Summary:
Original commit changeset: a367e3091254

Original Phabricator Diff: D26872981

Build breaks for some projects, including fizz:
```
folly/lang/Exception.cpp:64:3: error: ‘_Unwind_Ptr’ does not name a type
   64 |   _Unwind_Ptr catchTemp;
      |   ^~~~~~~~~~~
```

Differential Revision: D57676272

fbshipit-source-id: 4cd6c03f0e4c23c236482682c8d4b96ec3a75596