Use lldb.SBValue::GetError() for checking validity of SBValues in hhvm scripts
Summary:
Check for `GetError()` rather than just `IsValid()`, as the latter only indicates if the value contains a backing object from lldb_private namespace, while the former actually says if the value is safe to work with.

With these better checks, failing tests showed that I also needed to [fix a site](https://www.internalfb.com/code/fbsource/[18ad9c994a0c773b841a709132b1dfecebdce84b]/fbcode/hphp/tools/lldb/utils.py?lines=332) where a pointer is created, to go from `SBValue::CreateValueFromAddress` to `SBValue::CreateValueFromExpression` since the former creates a value from whatever is stored at the given address, while what we wanted there was to create a pointer to that address itself:
```
>>> addr = utils.get(ptr2, "m_data").unsigned & 0xffffffffffff
>>> addr
68730034896

# What I was doing before
>>> hex(ptr2.CreateValueFromAddress("(tmp)", addr, inner.GetPointerType()).unsigned)
'0xa5a5000200010000'(lldb) x -G4xw 0xa5a5000200010000
error: memory read failed for 0xa5a5000200010000

# What's now being done
>>> hex(ptr2.CreateValueFromExpression("(tmp)", f"({inner.GetPointerType()}) {addr}").unsigned)
'0x1000a11ad0'
(lldb) x -G4xw 0x1000a11ad0
0x1000a11ad0: 0x00010000 0xa5a50002 0x00000000 0x00000000
```

Reviewed By: clayborg

Differential Revision: D47809454

fbshipit-source-id: 30740612dd30a2e519ef51440ca1177c06afcae0