Fix failing build caused by missing parameter
Summary:
I think this was introduced by a change in the function signature in D16232479.

Fixes a build failure when running `buck build hphp/hack/src/...`

```
$ buck build hphp/hack/src/...
File "/data/users/coleerickson/fbsource-fbcode3/fbcode/hphp/hack/src/typing/typing_coercion.ml", line 145, characters 8-11:
Error: This expression has type 'weak4 -> 'weak5
       but an expression was expected of type
         Typing_utils.Env.env = Typing_env.env
```

Reviewed By: jewelpit

Differential Revision: D16402763

fbshipit-source-id: c1bdd77a52c424be95d415c99bbb432896e1ab85