Fix buck2 build error in xplat/thrift
Summary:
Error
```
[2023-04-03T10:54:13.480-07:00] Stderr: xplat/thrift/lib/cpp/test/Base64Test.cpp:37:6: error: no previous prototype for function 'checkEncoding' [-Werror,-Wmissing-prototypes]
[2023-04-03T10:54:13.480-07:00] void checkEncoding(uint8_t* data, int len) {
[2023-04-03T10:54:13.480-07:00]      ^' in /var/sandcastle/deployment/mount/53446/flib/intern/sandcastle/core/shell/SandcastleStatusDecoderBase.php:279
```

This function needs to be static for it to be considered a prototype

Differential Revision: D44649127

fbshipit-source-id: f1642ebc1e1738a919d0351edaf5311e96fc2a43