Require explicit truncating cast when constructing mstch::node from large integer type
Summary:
Previously, constructing a `mstch::node` from `int64_t` would silently truncate to `int`.

Since {D57946616}, it silently converts to `size_t` and then does a checked cast to `int`, throwing an error if the value is out of range.

After this diff, it won't compile. You must write a `static_cast<int>(…)` to make it clear at the call site that a truncation is taking place.

```lang=text,counterexample
fbcode/thrift/compiler/generate/t_mstch_rust_generator.cc:1659:12: error: conversion from 'int64_t' (aka 'long') to 'mstch::node' is ambiguous
    return const_value_->get_integer();
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
buck-out/v2/gen/fbcode/99cab575c71b0a4b/thrift/compiler/detail/mustache/__mustache__/buck-headers/thrift/compiler/detail/mustache/mstch.h:191:18: note: candidate constructor
  /* implicit */ node(std::size_t i);
                 ^
buck-out/v2/gen/fbcode/99cab575c71b0a4b/thrift/compiler/detail/mustache/__mustache__/buck-headers/thrift/compiler/detail/mustache/mstch.h:198:18: note: candidate constructor
  /* implicit */ node(int i) : base(i) {}
                 ^
1 error generated.
```

Reviewed By: iahs

Differential Revision: D58220426

fbshipit-source-id: 094fa0d8d981aafcd9da9ceb369e3fc03613d1b9