Avoid panic during oxidized_by_ref::typing_defs::Ty::from_ocamlrep
Summary:
The `Lazy` type in oxidized_by_ref is a stub. None of the values we've historically wanted to pass between Rust and OCaml have contained `Lazy.t` values, but it was useful to have a stub definition, since it allows files which happened to contain `Lazy` fields to be oxidized.

In `hh_single_type_check --type` mode (D33067353 (https://github.com/facebook/hhvm/commit/41fc8f2911028aad82b3f9c4beafc83b91963d29)), we want to convert `locl_ty`s to Rust values so that we can serialize them. Unfortunately, Reasons have been changed recently to possibly contain `Lazy` values (for performance reasons), so the panic when attempting to convert a `Lazy` from OCaml to Rust is a problem:

```
$ buck2 run @//mode/opt-clang //hphp/hack/src:hh_single_type_check -- --root ~/www --naming-table ~/www-naming.sql --type ~/www/flib/intern/hf/codemod_tools/core/HackAst.php

[2022-07-21 13:28:07.837] Loading naming table from SQLite...
[2022-07-21 13:28:07.838] Loaded local naming table changes: 0.000560
[2022-07-21 13:28:07.838] Updated reverse naming table entries: 0.000037
12root|flib/intern/hf/codemod_tools/core/HackAst.php\n
12root|flib/intern/hf/codemod_tools/core/HackAst.php\n
02root|flib/intern/hf/codemod_tools/core/HackAst.php
                                                    >*\InvariantViolationException

<several lines omitted>

02root|flib/intern/hf/codemod_tools/core/HackAst.php>*#
                                                       \TpNode
thread '<unnamed>' panicked at 'not implemented', hphp/hack/src/oxidized_by_ref/manual/lazy.rs:56:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Uncaught exception:

  (Failure "not implemented")

Raised by primitive operation at Typing_preorder_ser.encode_tys_as_stdout_lines.object#on_'ex in file "fbcode/hphp/hack/src/typing/serialization/typing_preorder_ser.ml", line 23, characters 29-66
Called from Aast.iter#on_expr in file "fbcode/hphp/hack/src/annotated_ast/aast.ml", line 20, characters 0-1023
Called from Aast.iter#on_Foreach in file "fbcode/hphp/hack/src/annotated_ast/aast.ml", line 20, characters 0-1023
Called from Aast.pp_class_const_kind.__1 in file "fbcode/hphp/hack/src/annotated_ast/aast.ml", line 20, characters 0-1023
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Aast.iter#on_If in file "fbcode/hphp/hack/src/annotated_ast/aast.ml", line 20, characters 0-1023
Called from Aast.pp_class_const_kind.__1 in file "fbcode/hphp/hack/src/annotated_ast/aast.ml", line 20, characters 0-1023
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Aast.iter#on_Shape.(fun) in file "fbcode/hphp/hack/src/annotated_ast/aast.ml", line 20, characters 0-1023
Called from Aast.iter#on_method_ in file "fbcode/hphp/hack/src/annotated_ast/aast.ml", line 20, characters 0-1023
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Aast.iter#on_class_ in file "fbcode/hphp/hack/src/annotated_ast/aast.ml", line 20, characters 0-1023
Called from Aast.iter#on_Class in file "fbcode/hphp/hack/src/annotated_ast/aast.ml", line 20, characters 0-1023
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Stdlib__Stream.iter.do_rec in file "stream.ml" (inlined), line 152, characters 33-38
Called from Stdlib__Stream.iter in file "stream.ml", line 155, characters 2-11
Called from Hh_single_type_check.main_hack.process in file "fbcode/hphp/hack/src/hh_single_type_check.ml", line 2828, characters 4-54
Called from Utils.try_finally in file "fbcode/hphp/hack/src/utils/core/utils.ml", line 213, characters 8-12
Re-raised at Exception.reraise in file "fbcode/hphp/hack/src/utils/core/exception.ml", line 36, characters 33-76
Called from Utils.try_finally in file "fbcode/hphp/hack/src/utils/core/utils.ml", line 217, characters 6-25
Called from Hh_single_type_check in file "fbcode/hphp/hack/src/hh_single_type_check.ml", line 2846, characters 2-77
```

We can't just force the `Lazy` value (i.e., run its closure to compute it) in the `FromOcamlRep` implementation, since it would involve calling back into the OCaml runtime. I think we could hold on to the `Lazy` closure and allow the Rust caller to force it when they know it's safe to call back into OCaml. But since we don't actually need the contents of the Lazy values in Reasons at this time, we can kick this can further down the road by making the contents of Lazy optional, and just assigning None when converting from OCaml.

Reviewed By: aorenste

Differential Revision: D38052236

fbshipit-source-id: fe31f61bdb4cc01057d783f1179ad53462ebee30