fix FunctionRef test under MSVC
Summary:
Address this failure:
```
FAILED: CMakeFiles/function_ref_test.dir/folly/test/FunctionRefTest.cpp.obj
folly\test\FunctionRefTest.cpp(250): warning C4822: 'folly::FunctionRef_Emptiness_Test::TestBody::NullptrTestableInSitu::NullptrTestableInSitu': local class member function does not have a body
folly\test\FunctionRefTest.cpp(250): warning C5046: 'folly::FunctionRef_Emptiness_Test::TestBody::NullptrTestableInSitu::NullptrTestableInSitu': Symbol involving type with internal linkage not defined
folly\test\FunctionRefTest.cpp(250): error C3640: 'folly::FunctionRef_Emptiness_Test::TestBody::NullptrTestableInSitu::NullptrTestableInSitu': a referenced or virtual member function of a local class must be defined
folly\test\FunctionRefTest.cpp(257): note: This diagnostic occurred in the compiler generated function 'folly::FunctionRef_Emptiness_Test::TestBody::NullptrTestableOnHeap::NullptrTestableOnHeap(std::nullptr_t)'
```

Reviewed By: Orvid

Differential Revision: D89229356

fbshipit-source-id: 5088825e0c76cc3c738654de72aa03dd669737e8