Make `require extends C` inside interfaces and traits a type error if C is final
Summary:
Currently, the following code is accepted by the type-checker:
```
<?hh // strict

final class C {}

interface I {
  require extends C;
}
```
but fatals at run time with
```
Fatal error: Interface 'I' requires extension of 'C', but C is not an extendable class in /data/users/manzyuk/fbsource/fbcode/hphp/hack/test/require_extends.php on line 4
```
Ditto if we replace `interface` with `trait`.  This diff make `require extends C` with a final class `C` a type error.

Reviewed By: kmeht

Differential Revision: D9239944

fbshipit-source-id: 3cc648eaf2a07e5206d36e46eee0564f98f5bc07