Remove unused variable
Summary:
Otherwise we get the following failure:

```
thrift/lib/cpp2/protocol/detail/Object.h:1086:14: error: variable 'ret' set but not used [-Werror,-Wunused-but-set-variable]
 1086 |     if (auto ret = operator()(value, buf)) {
      |              ^
1 error generated.
```

Differential Revision: D57298786

fbshipit-source-id: aac938ef9f27154cafb84d808b8db4f01efdbf10