fix @//mode/win fixtures_test failures from autogen comment
Summary:
Currently `buck2 test @//mode/win //thrift/compiler/test:fixture_test` fails with the below error.

This path is in the autogen comment, so no need to use system-dependent path separator. Therefore, should be safe to transform windows `'\'` to posix `'/'`.

```
AssertionError: Difference found in module_constants.cpp:
 --- .\thrift/compiler/test/fixtures\basic-python-capi\gen-cpp2\module_constants.cpp
+++ C:\Users\facebook\AppData\Local\Temp\tmpaiw50gw6\.\thrift/compiler/test/fixtures\basic-python-capi\gen-cpp2\module_constants.cpp
@@ -1,5 +1,5 @@
 /**
- * Autogenerated by Thrift for thrift/compiler/test/fixtures/basic-python-capi/src/module.thrift
+ * Autogenerated by Thrift for thrift\compiler\test\fixtures\basic-python-capi\src\module.thrift
  *
  * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
  *  generated nocommit
```

Reviewed By: iahs, Filip-F

Differential Revision: D46524718

fbshipit-source-id: 5d9ccf078abd16afe00d5104329a56f023487f51