Improve check for LLVM version in template type test
Summary:
Looks like (happily) LLVM19 behaves like 17 when generated dwarf for template types:
```
michristensen@devbig262 tools/lldb » HHVM=$(buck2 build 'fbcode//mode/dbg' -c hhvm.use_dwp=1 -c cxx.extra_cxxflags=-gpubnames -c fbcode.split-dwarf5=True -c hhvm.use_lowptr=0 -c fbcode.enable_simple_template_names=False fbcode//hphp/tools/lldb:hhvm_types_for_lldb_tests_pre_embed --show-full-output | cut -d " " -f 2)
Buck UI: https://www.internalfb.com/buck2/ca9f6135-9b00-421a-8250-a7c8aa818b6e
Network: Up: 0B  Down: 0B
Command: build.
Time elapsed: 1.6s
BUILD SUCCEEDED
michristensen@devbig262 tools/lldb » echo $HHVM
/data/users/michristensen/fbsource/buck-out/v2/gen/fbcode/7c9fd8c57fcc25f2/hphp/tools/lldb/__hhvm_types_for_lldb_tests_pre_embed__/hhvm_types_for_lldb_tests_pre_embed

michristensen@devbig262 tools/lldb » lldb $HHVM
>>> utils.Type("HPHP::VMFixedVector<HPHP::Func::ParamInfo>", lldb.target)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/data/users/michristensen/fbsource/fbcode/hphp/tools/lldb/utils.py", line 355, in Type
    assert ty is not None and ty.IsValid(), f"couldn't find type '{name}'"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: couldn't find type 'HPHP::VMFixedVector<HPHP::Func::ParamInfo>'

>>> utils.Type("HPHP::VMFixedVector<ParamInfo>", lldb.target)
typedef HPHP::VMFixedVector<ParamInfo>
```

Fixes test that broke with recent move to llvm 19: https://www.internalfb.com/intern/test/281475074377479?ref_report_id=0

Reviewed By: aperez

Differential Revision: D77469082

fbshipit-source-id: 5b44a60ce18ed85eaa2c4e35d3debf7f4516d706