Disallow wildcards in shape and tuple types when using `as` or `is` type assertions
Summary:
Wildcards (`_`) shouldn't be allowed in shape/tuple types when using `as` or `is` type assertions, since these throw an error at runtime.

Some example expressions that currently fatal at runtime that should also be rejected by the typechecker:

**Tuples**
```
$ cat -n tuples.php
     1  <?hh
     2
     3  function f(mixed $x) : void {
     4    $x is (_, int);
     5    $x is (int, (int, _));
     6    $x as (_, int);
     7    $x as (int, (int, _));
     8  }
     9
    10  <<__EntryPoint>>
    11  function main(): void {
    12    $x = tuple(3, 'hello');
    13    f($x);
    14  }

$ php tuples.php

Fatal error: "is" and "as" operators cannot be used with a generic type in /home/michristensen/scratch/wildcard/tuples.php on line 4
```

**Shapes**
```
$ cat -n shapes.php
     1  <?hh
     2
     3  function f(mixed $x) : void {
     4    $x is shape('y' => _);
     5    $x is shape('y' => int, 'z' => _);
     6    $x is shape('y' => shape('a' => _), 'z' => int);
     7    $x as shape('y' => _);
     8    $x as shape('y' => int, 'z' => _);
     9    $x as shape('y' => shape('a' => _), 'z' => int);
    10  }
    11
    12  <<__EntryPoint>>
    13  function main(): void {
    14    $x = shape('y' => 3);
    15    f($x);
    16  }

$ php shapes.php

Fatal error: "is" and "as" operators cannot be used with a generic type in /home/michristensen/scratch/wildcard/shapes.php on line 4
```

Here's some highlighted output from the new fix:

{F255164989}

{F255164981}

Reviewed By: Wilfred

Differential Revision: D22744163

fbshipit-source-id: c359e1b4eb483b740a13107cfa823dcdde719bb1