fix fbthrift oss failure for KeepAliveWatcher
Summary:
As titled, fix fbthrift oss failure for KeepAliveWatcher

D54007169 added a new file but missed in OSS and hence causing linking failures on fbthrift.

```
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/lib/libthriftcpp2.a(RocketClient.cpp.o): In function `apache::thrift::rocket::RocketClient::detachEventBase()':
RocketClient.cpp:(.text+0x90d): undefined reference to `apache::thrift::rocket::KeepAliveWatcher::detachEventBase()'
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/lib/libthriftcpp2.a(RocketClient.cpp.o): In function `apache::thrift::rocket::RocketClient::attachEventBase(folly::EventBase&)':
RocketClient.cpp:(.text+0x96e): undefined reference to `apache::thrift::rocket::KeepAliveWatcher::attachEventBase(folly::EventBase*)'
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/lib/libthriftcpp2.a(RocketClient.cpp.o): In function `apache::thrift::rocket::RocketClient::closeNowImpl()':
RocketClient.cpp:(.text+0x1409): undefined reference to `apache::thrift::rocket::KeepAliveWatcher::stop()'
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/lib/libthriftcpp2.a(RocketClient.cpp.o): In function `apache::thrift::rocket::RocketClient::~RocketClient()':
RocketClient.cpp:(.text+0x193c): undefined reference to `apache::thrift::rocket::KeepAliveWatcher::stop()'
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/lib/libthriftcpp2.a(RocketClient.cpp.o): In function `apache::thrift::rocket::RocketClient::handleFrame(std::unique_ptr<folly::IOBuf, std::default_delete<folly::IOBuf> >)':
RocketClient.cpp:(.text+0x6b60): undefined reference to `apache::thrift::rocket::KeepAliveWatcher::handleKeepaliveFrame(std::unique_ptr<folly::IOBuf, std::default_delete<folly::IOBuf> >)'
/data/sandcastle/temp/skycastle/fbcode_builder_getdeps/installed/fbthrift/lib/libthriftcpp2.a(RocketClient.cpp.o): In function `apache::thrift::rocket::RocketClient::RocketClient(folly::EventBase&, std::unique_ptr<folly::AsyncTransport, folly::DelayedDestruction::Destructor>, std::unique_ptr<apache::thrift::rocket::SetupFrame, std::default_delete<apache::thrift::rocket::SetupFrame> >, std::shared_ptr<std::experimental::fundamentals_v2::pmr::polymorphic_allocator<unsigned char> >)':
RocketClient.cpp:(.text+0x7945): undefined reference to `apache::thrift::rocket::KeepAliveWatcher::KeepAliveWatcher(folly::EventBase*, folly::AsyncTransport*, std::chrono::duration<long, std::ratio<1l, 1000l> >, std::chrono::duration<long, std::ratio<1l, 1000l> >)'
RocketClient.cpp:(.text+0x7995): undefined reference to `apache::thrift::rocket::KeepAliveWatcher::start(apache::thrift::rocket::SetupFrame*)'
```

Differential Revision: D54103061

fbshipit-source-id: 114109ab07cfeeb53bf174fcd110c770fc457bcf