Add InterceptorFrameworkMetadata.cpp to OSS cmake files
Summary:
Ran into an error building FBOSS OSS:

```
FAILED: sensor_service_client
: && /usr/bin/c++ -Wall -Werror -Wno-sign-compare -Wno-maybe-uninitialized -Wno-deprecated-declarations -Os -DNDEBUG  CMakeFiles/sensor_service_client.dir/fboss/platform/sensor_service/SensorServicePlainTextClient.cpp.o -o sensor_service_client  -Wl,-rpath,/data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/gflags-8ULlaXE-NsRYN4KRrguMdnoehmyp4gCyuXmPFU6gib4/lib:/data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/glog-rUIVfhWAxjUU1hs2RqFHIbKxp2AqiZ5_msLD7BRLe94/lib64  libsensor_service_cpp2.a  libplatform_utils.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/folly/lib/libfolly.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/libthriftcpp2.a  libfboss_cpp2.a  libsensor_config_cpp2.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_server_async_tran.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_server.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_server_state.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_dsr_frontend.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_dsr_types.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_fizz_handshake.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_transport.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_buf_accessor.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_state_datagram_handler.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_batch_writer.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_cc_algo.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_codec_pktrebuilder.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_ack_scheduler.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_happyeyeballs.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_async_udp_socket.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_events.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_looper.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_observer.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_state_ack_handler.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_loss.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_state_pacing_functions.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_state_simple_frame_functions.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_state_functions.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_codec_pktbuilder.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_state_stream.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_flowcontrol.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_qlogger.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_state_stream_functions.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_state_machine.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_codec.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_handshake.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_codec_packet_number_cipher.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_codec_decode.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_codec_types.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_exception.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_bufutil.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_transport_knobs.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_constants.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/mvfst/lib/libmvfst_transport_settings_functions.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/libthriftcpp2.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/libthriftfrozen2.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/libthriftmetadata.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/libthriftanyrep.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/libthrifttype.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/libthriftprotocol.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/libthriftprotocol.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/libasync.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/libruntime.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/libtransport.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/librpcmetadata.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/libconcurrency.a  /lib64/libzstd.so  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/wangle/lib/libwangle.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/fizz/lib/libfizz.a  /usr/lib64/libsodium.so  /usr/lib64/libz.so  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/liboqs-QsrHXiBwhcEXVTsMU8UXQe4EiK3ckF8bovsRbTHucnc/lib64/liboqs.a  /usr/lib64/librt.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/libthrift-core.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/libthrifttyperep.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/libthriftannotation.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/libserverdbginfo.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/folly/lib/libfolly.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/fmt-PHKdOxeJ8YXUfUGVeu4FWiWcBclLwI78qrkZrx2qWNQ/lib64/libfmt.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/boost-RcgHfb4Q46p_aCWaYEbW2xsov6aNJW9cwn_O3dK4xAE/lib/libboost_context.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/boost-RcgHfb4Q46p_aCWaYEbW2xsov6aNJW9cwn_O3dK4xAE/lib/libboost_filesystem.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/boost-RcgHfb4Q46p_aCWaYEbW2xsov6aNJW9cwn_O3dK4xAE/lib/libboost_atomic.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/boost-RcgHfb4Q46p_aCWaYEbW2xsov6aNJW9cwn_O3dK4xAE/lib/libboost_program_options.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/boost-RcgHfb4Q46p_aCWaYEbW2xsov6aNJW9cwn_O3dK4xAE/lib/libboost_regex.a  -licudata  -licui18n  -licuuc  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/boost-RcgHfb4Q46p_aCWaYEbW2xsov6aNJW9cwn_O3dK4xAE/lib/libboost_system.a  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/boost-RcgHfb4Q46p_aCWaYEbW2xsov6aNJW9cwn_O3dK4xAE/lib/libboost_thread.a  /usr/lib64/libdouble-conversion.so  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/gflags-8ULlaXE-NsRYN4KRrguMdnoehmyp4gCyuXmPFU6gib4/lib/libgflags.so.2.2.2  /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/glog-rUIVfhWAxjUU1hs2RqFHIbKxp2AqiZ5_msLD7BRLe94/lib64/libglog.so  /usr/lib64/libevent.so  /usr/lib64/libz.so  /usr/lib64/libssl.so  /usr/lib64/libcrypto.so  /usr/lib64/libbz2.so  /usr/lib64/liblzma.so  /usr/lib64/liblz4.so  /usr/lib64/libzstd.so  /usr/lib64/libsnappy.so  /usr/lib64/libdwarf.so  /usr/lib64/libiberty.a  /usr/lib64/libaio.so  /usr/lib64/libsodium.so  -ldl  /usr/lib64/libunwind.so  /usr/lib64/libxxhash.so  /usr/lib64/libre2.so && :
/usr/bin/ld: /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/libasync.a(ContextStack.cpp.o): in function `apache::thrift::ContextStack::ContextStack(std::shared_ptr<std::vector<std::shared_ptr<apache::thrift::TProcessorEventHandler>, std::allocator<std::shared_ptr<apache::thrift::TProcessorEventHandler> > > > const&, char const*, char const*, void**, apache::thrift::server::TConnectionContext*)':
ContextStack.cpp:(.text+0x7a7): undefined reference to `apache::thrift::detail::initializeInterceptorFrameworkMetadataStorage'
/usr/bin/ld: ContextStack.cpp:(.text+0x7b1): undefined reference to `apache::thrift::detail::initializeInterceptorFrameworkMetadataStorage'
/usr/bin/ld: /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/fbthrift/lib/libasync.a(ContextStack.cpp.o): in function `apache::thrift::ContextStack::getInterceptorFrameworkMetadata()':
ContextStack.cpp:(.text+0xf32): undefined reference to `apache::thrift::detail::serializeFrameworkMetadata'
/usr/bin/ld: ContextStack.cpp:(.text+0xf3c): undefined reference to `apache::thrift::detail::serializeFrameworkMetadata'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
Command '['/usr/bin/cmake', '--build', '/data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/build/fboss', '--target', 'sensor_service_client', '--config', 'RelWithDebInfo', '-j', '32']' returned non-zero exit status 1.
!! Failed
```

The issue seems to be that new source files are missing from the OSS fbthrift library (these new sources were added in D69807758.

Reviewed By: evanjzou

Differential Revision: D70569613

fbshipit-source-id: d8065cd703a737bebe19536542dfe06da18c6ea5