fix bug on unknown field
Summary:
When a user gives a bad field name, it exposes a bug in `Struct.__init__`.
```
File "thrift.python/types.pyx", line 1118, in thrift.python.types.Struct.__call__
TypeError: 'dict_keys' object is not subscriptable
```

Instead of subscripting keys, just format all the bad keys as a list.

Reviewed By: yoney

Differential Revision: D67347012

fbshipit-source-id: 1bddf24505d0602a824535785c46e9f143defac3