Include requisite C++ headers in hhbc-ast CMake target (#8987)
Summary:
Was hitting some errors in the diff on top of this one:
```
/data/sandcastle/temp/hhvm-cmake-build/build/hphp/hack/src/hackc/hhbc-ast.h:1657:3: error: ‘TypeConstraintFlags’ does not name a type; did you mean ‘Constraint’?
   TypeConstraintFlags flags;
   ^~~~~~~~~~~~~~~~~~~
   Constraint
/data/sandcastle/temp/hhvm-cmake-build/build/hphp/hack/src/hackc/hhbc-ast.h:1758:3: error: ‘Attr’ does not name a type; did you mean ‘Str’?
   Attr attrs;
   ^~~~
   Str
/data/sandcastle/temp/hhvm-cmake-build/build/hphp/hack/src/hackc/hhbc-ast.h:1805:3: error: ‘Attr’ does not name a type; did you mean ‘Str’?
   Attr attrs;
   ^~~~
   Str
/data/sandcastle/temp/hhvm-cmake-build/build/hphp/hack/src/hackc/hhbc-ast.h:1810:3: error: ‘Attr’ does not name a type; did you mean ‘Str’?
```

Need to include the attr.h and type-constraint-flag.h header files in hhbc-ast.h CMake target.

Also delete a redundant target.

Pull Request resolved: https://github.com/facebook/hhvm/pull/8987

Reviewed By: fredemmott

Differential Revision: D34048712

fbshipit-source-id: eedd800ead29c9959723c7852f5976ac31908e24