Implement stronger rust-type comparison
Summary:
This is required for supporting newtypes inside `rust.Type`, such as in this code:

```lang=thrift
rust.NewType
typedef string Id

struct Repro {
  rust.Type{name = "rustc_hash::FxHashSet"}
  1: set<Id> ids;
  rust.Type{name = "rustc_hash::FxHashSet"}
  2: set<string> strings;
}
```

Previously the Rust Thrift implementation would produce `LocalImpl` impls based on comparing only 2 things:

1. the field-level or type-level Rust type string (`get_type_annotation`)

2. the Thrift type name ignoring typedefs and annotations (`get_resolved_name`)

If both of those things matched, as they do in the above snippet, only a single `LocalImpl` would be generated, resulting in a compile error for the other field.

```lang=log,counterexample
error[E0308]: mismatched types
   --> fbcode/scripts/dtolnay/thrift/lib.rs:114:40
    |
114 |         crate::r#impl::rs_thrift_write(&self.strings, p);
    |         ------------------------------ ^^^^^^^^^^^^^ expected `&HashSet<Id, FxBuildHasher>`, found `&HashSet<String, FxBuildHasher>`
    |         |
    |         arguments to this function are incorrect
    |
    = note: expected reference `&HashSet<Id, _>`
               found reference `&HashSet<std::string::String, _>`
note: function defined here
   --> fbcode/scripts/dtolnay/thrift/lib.rs:241:19
    |
241 |     pub(crate) fn rs_thrift_write<T, P>(value: &T, p: &mut P)
    |                   ^^^^^^^^^^^^^^^       ---------

error[E0308]: `?` operator has incompatible types
   --> fbcode/scripts/dtolnay/thrift/lib.rs:146:34
    |
146 | ... = ::anyhow::Context::context(crate::r#impl::rs_thrift_read(p), ::fbthrift::errors::DeserializingFieldError { field: "strings", strct: "Repro"})?;
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `HashSet<String, FxBuildHasher>`, found `HashSet<Id, FxBuildHasher>`
    |
    = note: `?` operator cannot convert from `HashSet<Id, _>` to `HashSet<std::string::String, _>`
    = note: expected struct `HashSet<std::string::String, _>`
               found struct `HashSet<Id, _>`

error[E0308]: `?` operator has incompatible types
   --> fbcode/scripts/dtolnay/thrift/lib.rs:161:69
    |
161 | ... = ::anyhow::Context::context(crate::r#impl::rs_thrift_read(p), ::fbthrift::errors::DeserializingFieldError { field: "strings", strct: "Repro"})?,
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `HashSet<String, FxBuildHasher>`, found `HashSet<Id, FxBuildHasher>`
    |
    = note: `?` operator cannot convert from `HashSet<Id, _>` to `HashSet<std::string::String, _>`
    = note: expected struct `HashSet<std::string::String, _>`
               found struct `HashSet<Id, _>`
```

This diff reimplements the `rust_type_less` comparator to more extensively distinguish types that are not equal, taking into account `rust.NewType` annotations, `rust.Adapter` annotations, and `rust.Type` annotations while stepping through unannotated typedefs.

For the `rust.Adapter` case more work is needed elsewhere in the Rust whisker templates to fully support this, but this diff is enough to make many cases work with just the existing templates.

Reviewed By: hchokshi

Differential Revision: D117412164

fbshipit-source-id: 7e04fad7b3f57f8f7b3675d64c5c8d1c0959cd79