Fix -Wimplicit-int-enum-cast
Summary:
An error is produced when building using the 21 compiler. It introduces a new warning `-Wimplicit-int-enum-cast` and this diff fixes the warning by static casting.

The enum's underlying type is uint16_t, same as what getProtocolId() returns. So the value started as PROTOCOL_TYPES, and then stored as uint16_t, and this diff is casting it back to PROTOCOL_TYPES.

```
Action failed: fbcode//tupperware/agent/twac:task_lookup (cxx_compile TaskLookup.cpp)
Remote command returned non-zero exit code 1
Reproduce locally: `frecli cas download-action 1546d0edff16786a282daa99253d752dd7177244db753b8610d645fed58f7098:148`
stdout:
stderr:
In file included from fbcode/tupperware/agent/twac/TaskLookup.cpp:3:
In file included from buck-out/v2/gen/fbcode/tupperware/agent/twac/__task_lookup__/400b028fb5d8d89e/buck-headers/tupperware/agent/twac/TaskLookup.h:7:
In file included from buck-out/v2/gen/fbcode/tupperware/agent/twac/__client_wrapper__/0580f77e5afbe354/buck-headers/tupperware/agent/twac/ClientWrapper.h:5:
In file included from buck-out/v2/gen/fbcode/tupperware/common/cpp_cli/__client_wrapper__/61c2323c3e08e664/buck-headers/tupperware/common/cpp_cli/ClientWrapper.h:10:
buck-out/v2/gen/fbcode/thrift/lib/cpp2/async/__header_client_channel__/821df9a29f7d6052/buck-headers/thrift/lib/cpp2/async/HeaderClientChannel.h:390:64: error: implicit conversion from 'uint16_t' (aka 'unsigned short') to enumeration type 'const protocol::PROTOCOL_TYPES' is invalid in C++ [-Werror,-Wimplicit-int-enum-cast]
  390 |     const protocol::PROTOCOL_TYPES protocolId_{headerChannel_->getProtocolId()};
      |                                               ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
1 error generated.
Buck UI: https://www.internalfb.com/buck2/f3faefda-2685-4e3f-ae67-8e5a6d26db89
Network: Up: 139MiB  Down: 532MiB  (reSessionID-52e515f9-e3b6-4343-91e5-1f2ca0280a34)
Loading targets.   Remaining      0/747
Analyzing targets. Remaining      0/29002
Executing actions. Remaining      0/170390
Command: build.    Finished 240 local, 20809 remote, 21574 cache (51% hit)
Time elapsed: 1:20.0s
BUILD FAILED
Failed to build 'fbcode//tupperware/agent/twac:task_lookup (cfg:opt-linux-x86_64-fbcode-platform010-clang21-no-san#28bd6123ff0e74bd)'

Reviewed By: iahs

Differential Revision: D90688892

fbshipit-source-id: 91c463df0b253c7adb82df9ffdc0a41a64172f97