Fix boost include in ServerProtocolTest.cpp
Summary:
Our linux builds are failing with
```
FAILED: CMakeFiles/ServerProtocolTest.dir/server/test/ServerProtocolTest.cpp.o
/usr/bin/c++ -DBOOST_ATOMIC_NO_LIB -DBOOST_CONTEXT_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -DFMT_LOCALE -DGFLAGS_IS_A_DLL=0 -DServerProtocolTest_EXPORTS -I/data/sandcastle/temp/fbcode_builder_getdeps/shipit/fizz -isystem /data/sandcastle/temp/fbcode_builder_getdeps/installed/googletest--Rf6a0YuWzpSNb8J6YP8A1yaTmtlzm99K6Pr31k76q8/include -isystem /data/sandcastle/temp/fbcode_builder_getdeps/installed/folly/include -isystem /data/sandcastle/temp/fbcode_builder_getdeps/installed/libsodium-lV3pDTszmvVg9l3JEXG6GQP37s22kvqKUv9Ei7LXXjE/include -isystem /data/sandcastle/temp/fbcode_builder_getdeps/installed/zstd-34zeN1X2EXXJjW_kBHbWFDcJKUX7qIymtbgMChhYybU/include -isystem /data/sandcastle/temp/fbcode_builder_getdeps/installed/boost-hbTF0CeS6C_9h4fL1Z7rlqAjjxj5BDqLzuDUNFPU7Gg/include -isystem /data/sandcastle/temp/fbcode_builder_getdeps/installed/double-conversion-C5SxN7MCGyk8EO5zD4 (https://github.com/facebook/hhvm/commit/6a7bba95f60a8876e892d555fe932b19ace362dd)gEiNoC1ZlweP5OhAsUc8Naefk/include -isystem /data/sandcastle/temp/fbcode_builder_getdeps/installed/gflags-SvnGa2G313OeptpCW8QajZfcnxJXuSDX9t9k7ICeAkM/include -isystem /data/sandcastle/temp/fbcode_builder_getdeps/installed/glog-z-2lCVVPfSSfqcOP6uURKAreedZV9StCFhYn2tdWukA/include -isystem /data/sandcastle/temp/fbcode_builder_getdeps/installed/libevent-qUQq83wcPkhe_6jtFWr9cUzfL5YRqTn_Lw2O5tLT0uY/include -isystem /data/sandcastle/temp/fbcode_builder_getdeps/installed/xz-6MpBUUPVv0IAS01T0bUrmOSaL7YlwgqolwiGP53uLsM/include -isystem /data/sandcastle/temp/fbcode_builder_getdeps/installed/lz4-W7hRr0bzntVWO0etB8u7mMGnbSMVBJUHidLALBvhtAw/include -isystem /data/sandcastle/temp/fbcode_builder_getdeps/installed/snappy-7sa-uNkAp8iniiyn6pjY7hqBPoCkqZywNgPRuZPoa9k/include -isystem /usr/include/libdwarf -isystem /usr/include/libiberty -isystem /data/sandcastle/temp/fbcode_builder_getdeps/installed/fmt-ZgGwQuWdrrcdIDtyIT5-NI42fdMSor_WUMS4TTmeh-U/include -isystem /data/sandcastle/temp/fbcode_builder_getdeps/installed/zlib-jPydpWXuNfkGVwtlrRDg7Xx-4hISBGuWjeGtGYsXEn0/include -O2 -g -DNDEBUG -fPIE -Wno-inconsistent-missing-override -std=c++17 -MD -MT CMakeFiles/ServerProtocolTest.dir/server/test/ServerProtocolTest.cpp.o -MF CMakeFiles/ServerProtocolTest.dir/server/test/ServerProtocolTest.cpp.o.d -o CMakeFiles/ServerProtocolTest.dir/server/test/ServerProtocolTest.cpp.o -c /data/sandcastle/temp/fbcode_builder_getdeps/shipit/fizz/fizz/server/test/ServerProtocolTest.cpp
/data/sandcastle/temp/fbcode_builder_getdeps/shipit/fizz/fizz/server/test/ServerProtocolTest.cpp: In member function ‘virtual void fizz::server::test::ServerProtocolTest_AsyncKeyExchangeTest_Test::TestBody()’:
/data/sandcastle/temp/fbcode_builder_getdeps/shipit/fizz/fizz/server/test/ServerProtocolTest.cpp:6586:25: error: ‘strict_get’ was not declared in this scope
   auto& actionsFuture = strict_get<folly::SemiFuture<Actions>>(asyncActions);
                         ^~~~~~~~~~
/data/sandcastle/temp/fbcode_builder_getdeps/shipit/fizz/fizz/server/test/ServerProtocolTest.cpp:6586:25: note: suggested alternative:
In file included from /data/sandcastle/temp/fbcode_builder_getdeps/installed/boost-hbTF0CeS6C_9h4fL1Z7rlqAjjxj5BDqLzuDUNFPU7Gg/include/boost/variant.hpp:22,
                 from /data/sandcastle/temp/fbcode_builder_getdeps/shipit/fizz/fizz/server/Actions.h:11,
                 from /data/sandcastle/temp/fbcode_builder_getdeps/shipit/fizz/fizz/server/ServerProtocol.h:17,
                 from /data/sandcastle/temp/fbcode_builder_getdeps/shipit/fizz/fizz/server/test/ServerProtocolTest.cpp:22:
/data/sandcastle/temp/fbcode_builder_getdeps/installed/boost-hbTF0CeS6C_9h4fL1Z7rlqAjjxj5BDqLzuDUNFPU7Gg/include/boost/variant/get.hpp:284:1: note:   ‘boost::strict_get’
 strict_get(
 ^~~~~~~~~~
/data/sandcastle/temp/fbcode_builder_getdeps/shipit/fizz/fizz/server/test/ServerProtocolTest.cpp:6586:61: error: expected primary-expression before ‘>’ token
   auto& actionsFuture = strict_get<folly::SemiFuture<Actions>>(asyncActions);
                                                             ^~
```
At first, I thought this might be because `strict_get` isn't available in that environment's Boost dependency. From what I can tell, we're running with 1.78.0 and `strict_get` has been availble since at least 1.59.0, see [here](https://www.boost.org/doc/libs/1_59_0/doc/html/boost/strict_get.html).

Reviewed By: kylemirz, mingtaoy

Differential Revision: D39442347

fbshipit-source-id: 012479059f09f7db3736690d66a676786370f31a