Deduplicate LocalImpl among field-level @rust.Type
Summary:
This code previously performed deduplication for type-level `rust.Type` annotations:

```lang=thrift
rust.Type{name = "rustc_hash::FxHashMap"}
typedef map<string, StackTrace> HashToStackTraceMap

struct StackTraceHashResolver {
  1: HashToStackTraceMap hashToStackTraceMap;
}

rust.Type{name = "rustc_hash::FxHashMap"}
typedef map<string, StackTrace> StackTraces

struct Properties {
  6: StackTraces stacktraces;
}
```

But not field-level `rust.Type` annotations, or between type-level and field-level annotations, resulting in colliding `LocalImpl` impls.

```lang=thrift
struct StackTraceHashResolver {
  rust.Type{name = "rustc_hash::FxHashMap"}
  1: map<string, StackTrace> hashToStackTraceMap;
}

struct Properties {
  rust.Type{name = "rustc_hash::FxHashMap"}
  6: map<string, StackTrace> stacktraces;
}
```

```lang=thrift
rust.Type{name = "rustc_hash::FxHashMap"}
typedef map<string, StackTrace> HashToStackTraceMap

struct StackTraceHashResolver {
  1: HashToStackTraceMap hashToStackTraceMap;
}

struct Properties {
  rust.Type{name = "rustc_hash::FxHashMap"}
  6: map<string, StackTrace> stacktraces;
}
```

```lang=log,counterexample
error[E0119]: conflicting implementations of trait `Serialize<_>` for type `LocalImpl<HashMap<std::string::String, StackTrace, FxBuildHasher>>`
    --> fbcode/artillery/thrift/lib.rs:3511:5
     |
3449 | /     impl<P> ::fbthrift::Serialize<P> for LocalImpl<::rustc_hash::FxHashMap<::std::string::String, crate::types::StackTrace>>
3450 | |     where
3451 | |         P: ::fbthrift::ProtocolWriter,
     | |______________________________________- first implementation here
...
3511 | /     impl<P> ::fbthrift::Serialize<P> for LocalImpl<::rustc_hash::FxHashMap<::std::string::String, crate::types::StackTrace>>
3512 | |     where
3513 | |         P: ::fbthrift::ProtocolWriter,
     | |______________________________________^ conflicting implementation for `LocalImpl<HashMap<std::string::String, StackTrace, FxBuildHasher>>`
```

Reviewed By: hchokshi

Differential Revision: D117318441

fbshipit-source-id: 765204bc86f41cb0f7bb57e9d1db813289f0b637