Include ranges.h in parse_ast.cc
Summary:
Tried building OSS fbthrift via:
```
https_proxy=fwdproxy:8080 http_proxy=fwdproxy:8080 ./opensource/fbcode_builder/getdeps.py build --allow-system-packages --extra-cmake-defines='{"CMAKE_BUILD_TYPE": "MinSizeRel", "CMAKE_CXX_STANDARD": "20", "RANGE_V3_EXAMPLES": "OFF"}' --num-jobs 32 fbthrift
```

results in the following error:
```
FAILED: thrift/compiler/CMakeFiles/compiler_lib.dir/parse/parse_ast.cc.o
/usr/bin/c++ -DTHRIFT_HAVE_LIBSNAPPY=0 -I/data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/shipit/fbthrift/. -I/data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/build/fbthrift -I/data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/gflags-8ULlaXE-NsRYN4KRrguMdnoehmyp4gCyuXmPFU6gib4/include -I/data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/glog-rUIVfhWAxjUU1hs2RqFHIbKxp2AqiZ5_msLD7BRLe94/include -isystem /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/fmt-PHKdOxeJ8YXUfUGVeu4FWiWcBclLwI78qrkZrx2qWNQ/include -isystem /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/installed/boost-RcgHfb4Q46p_aCWaYEbW2xsov6aNJW9cwn_O3dK4xAE/include -Os -DNDEBUG -std=c++20 -fcoroutines -MD -MT thrift/compiler/CMakeFiles/compiler_lib.dir/parse/parse_ast.cc.o -MF thrift/compiler/CMakeFiles/compiler_lib.dir/parse/parse_ast.cc.o.d -o thrift/compiler/CMakeFiles/compiler_lib.dir/parse/parse_ast.cc.o -c /data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/shipit/fbthrift/thrift/compiler/parse/parse_ast.cc
/data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/shipit/fbthrift/thrift/compiler/parse/parse_ast.cc: In member function ‘void apache::thrift::compiler::{anonymous}::ast_builder::validate_not_ambiguous_enum(apache::thrift::compiler::source_location, const string&)’:
/data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/shipit/fbthrift/thrift/compiler/parse/parse_ast.cc:233:39: error: ‘join’ is not a member of ‘fmt’
  233 |                   fmt::to_string(fmt::join(possible_enums, ", ")));
      |                                       ^~~~
ninja: build stopped: subcommand failed.
Command '['/usr/bin/cmake', '--build', '/data/users/paulcruz74/scratch/dataZusersZpaulcruz74Zfbsource/fbcode_builder_getdeps/build/fbthrift', '--target', 'install', '--config', 'RelWithDebInfo', '-j', '32']' returned non-zero exit status 1.
!! Failed
```

Buck builds seem to target fmt lib 8.x, while open source builds use 11.0.2 (https://fburl.com/code/1juttkk3), where the definition for `fmt::join` has moved to `ranges.h`.

Differential Revision: D70185950

fbshipit-source-id: 38f6f93da2cec00a4ee71da61ed54bb872ee2624