Replace FOLLY_ERASE with FOLLY_ALWAYS_INLINE to fix UniqueHashKey error
Summary:
Get the following error (full log P2054712740) and try to fix:
```
folly/hash/UniqueHashKey.cpp:176:56: error: 'visibility' attribute ignored [-Werror=attributes]
  176 |     span<detail::unique_hash_key_item const> const in) noexcept {
      |                                                        ^~~~~~~~
```

Replace FOLLY_ERASE with FOLLY_ALWAYS_INLINE for static function unique_hash_key_hash_items in UniqueHashKey.cpp since FOLLY_ERASE includes FOLLY_ATTR_VISIBILITY_HIDDEN, which conflicts with the static keyword.

Reviewed By: yfeldblum

Differential Revision: D87812203

fbshipit-source-id: 1680e7847bdb62148c2022e9f63c0cf5a263eee5