fix build with boost-1.69.0
Summary:
Add a missing header to fix build errors with the latest boost release.
```lang=bash
hphp/runtime/vm/as.cpp: In member function 'std::__cxx11::string HPHP::{anonymous}::AsmState::displayStackDepth()':
hphp/runtime/vm/as.cpp:554:24: error: aggregate 'std::ostringstream stack' has incomplete type and cannot be defined
hphp/runtime/vm/as.cpp: In function 'std::unique_ptr<HPHP::UnitEmitter> HPHP::assemble_string(const char*, int, const char*, const HPHP::MD5&, const HPHP::Native::FuncTable&, bool, HPHP::AsmCallbacks*)':
hphp/runtime/vm/as.cpp:3507:43: error: incomplete type 'std::istringstream' {aka 'std::__cxx11::basic_istringstream<char>'} used in nested name specifier
hphp/runtime/vm/as.cpp:3507:72: error: incomplete type 'std::istringstream' {aka 'std::__cxx11::basic_istringstream<char>'} used in nested name specifier
hphp/runtime/vm/as.cpp:3508:42: error: variable 'std::istringstream instr' has initializer but incomplete type
hphp/runtime/vm/as.cpp: In function 'HPHP::AsmResult HPHP::assemble_expression(HPHP::UnitEmitter&, HPHP::FuncEmitter*, int, const string&)':
hphp/runtime/vm/as.cpp:3535:41: error: incomplete type 'std::istringstream' {aka 'std::__cxx11::basic_istringstream<char>'} used in nested name specifier
hphp/runtime/vm/as.cpp:3535:70: error: incomplete type 'std::istringstream' {aka 'std::__cxx11::basic_istringstream<char>'} used in nested name specifier
hphp/runtime/vm/as.cpp:3536:26: error: variable 'std::stringstream sstr' has initializer but incomplete type
```

Reviewed By: markw65

Differential Revision: D13803421

fbshipit-source-id: 4e5f3b6dd80beddeed3936e83b976076dd5860e5