Add FFI for naming table asynchronous build
Summary:
Add FFI for OCaml to call into the Rust naming table builder. Since it's difficult to pass an OCaml callback to Rust land at the moment, I've opted for a poll-based design.

I suspect there might be a more elegant or direct way to express `BuildProgress`. Would be happy to change it to something more idiomatic if so!

Note: I was getting errors like
```
Entering directory '/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/fbcode/hphp'
File "hack/src/hh_naming_table_builder/dune", line 7, characters 0-247:
 7 | (rule
 8 |  (targets libhh_naming_table_builder_ffi.a)
 9 |  (deps
10 |   (source_tree %{workspace_root}/hack/src))
11 |  (locks /cargo)
12 |  (action
13 |   (run
14 |    %{workspace_root}/hack/scripts/invoke_cargo.sh
15 |    hh_naming_table_builder_ffi
16 |    hh_naming_table_builder_ffi)))
error: package ID specification `hh_naming_table_builder_ffi` did not match any packages
```
The solution was to add an entry for `hh_naming_table_builder_ffi` under `$FBCODE/hphp/hack/src/Cargo.toml`, and re-running `arc autocargo`. That seemed to have added the `ffi` Cargo library to the main Hack `Cargo.lock` file, which probably exposed it to dune?

Reviewed By: ljw1004

Differential Revision: D43739475

fbshipit-source-id: d00302f58c7d93756cdf1b0d85b4f5c765d58956