Fix unsued variable warnings in OSS build
Summary:
We are getting an unused variable warnings in the OSS build after
moving maps and sets out of Utils

```
File "utils/collections/myMap.ml", line 60, characters 27-28:
Warning 27: unused variable v.
File "utils/collections/myMap.ml", line 61, characters 27-28:
Warning 27: unused variable k.
File "utils/collections/myMap.ml", line 1:
Error: Some fatal warnings were triggered (2 occurrences)
Command exited with code 2.
```

Reviewed By: mroch

Differential Revision: D2917017

fb-gh-sync-id: 7a9e2bf7e29144b4a654978758f9daedad303cc2
shipit-source-id: 7a9e2bf7e29144b4a654978758f9daedad303cc2