Fix unused assignments in Rust 1.92
Summary:
```lang=log,counterexample
Action failed: fbcode//hphp/hack/src/utils:ocaml_helper (rustc check)

error: value assigned to `n` is never read
   --> fbcode/hphp/hack/src/utils/ocaml_helper.rs:184:9
    |
184 |         n = 0;
    |         ^^^^^
    |
    = help: maybe it is overwritten before being read?
    = note: `-D unused-assignments` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(unused_assignments)]`

error: value assigned to `n` is never read
   --> fbcode/hphp/hack/src/utils/ocaml_helper.rs:189:21
    |
189 |                     n += 1;
    |                     ^^^^^^
    |
    = help: maybe it is overwritten before being read?

error: value assigned to `n` is never read
   --> fbcode/hphp/hack/src/utils/ocaml_helper.rs:194:21
    |
194 |                     n += 1;
    |                     ^^^^^^
    |
    = help: maybe it is overwritten before being read?

error: value assigned to `n` is never read
   --> fbcode/hphp/hack/src/utils/ocaml_helper.rs:199:21
    |
199 |                     n += 1;
    |                     ^^^^^^
    |
    = help: maybe it is overwritten before being read?

error: value assigned to `n` is never read
   --> fbcode/hphp/hack/src/utils/ocaml_helper.rs:204:21
    |
204 |                     n += 1;
    |                     ^^^^^^
    |
    = help: maybe it is overwritten before being read?

error: value assigned to `n` is never read
   --> fbcode/hphp/hack/src/utils/ocaml_helper.rs:209:21
    |
209 |                     n += 1;
    |                     ^^^^^^
    |
    = help: maybe it is overwritten before being read?

error: value assigned to `n` is never read
   --> fbcode/hphp/hack/src/utils/ocaml_helper.rs:215:21
    |
215 |                     n += 1;
    |                     ^^^^^^
    |
    = help: maybe it is overwritten before being read?

error: value assigned to `n` is never read
   --> fbcode/hphp/hack/src/utils/ocaml_helper.rs:217:21
    |
217 |                     n += 1;
    |                     ^^^^^^
    |
    = help: maybe it is overwritten before being read?

error: value assigned to `n` is never read
   --> fbcode/hphp/hack/src/utils/ocaml_helper.rs:219:21
    |
219 |                     n += 1;
    |                     ^^^^^^
    |
    = help: maybe it is overwritten before being read?

error: value assigned to `n` is never read
   --> fbcode/hphp/hack/src/utils/ocaml_helper.rs:223:13
    |
223 |             n += 1;
    |             ^^^^^^
    |
    = help: maybe it is overwritten before being read?
```

Reviewed By: cjlongoria

Differential Revision: D92357029

fbshipit-source-id: 588647a3ad7b56338b4512e32ae74d78a7eaee82