replace # comments with // in hphp/test
Summary:
Using codemod in D24453833

```
fbgs -sl -f 'hphp/test/.*\.php$' '#' > ~/fbgs
cat ~/fbgs | sed -e 's#^#/data/users/viratyosin/fbsource/fbcode/#' | phps PoundCommentCodemod --stdin 2>&1 | tee ~/tmp
```

```
Skipping file due to a parse exception
	Path: /data/users/viratyosin/fbsource/fbcode/hphp/test/quick/parse_fail_strict_hashbang_whitespace_start.php
	Exception: Failed to parse tree for path `/data/users/viratyosin/fbsource/fbcode/hphp/test/quick/parse_fail_strict_hashbang_whitespace_start.php`
Skipping file due to a parse exception
	Path: /data/users/viratyosin/fbsource/fbcode/hphp/test/slow/hashbang.php
	Exception: Failed to parse tree for path `/data/users/viratyosin/fbsource/fbcode/hphp/test/slow/hashbang.php`
Skipping file due to an exception.
	Path: /data/users/viratyosin/fbsource/fbcode/hphp/test/slow/hash_not_bang.php
	Exception: HH\Lib\C\firstx: Expected at least one element.
Skipping file due to a parse exception
	Path: /data/users/viratyosin/fbsource/fbcode/hphp/test/slow/hashbang_regression.php
	Exception: Failed to parse tree for path `/data/users/viratyosin/fbsource/fbcode/hphp/test/slow/hashbang_regression.php`
Skipping file due to a parse exception
	Path: /data/users/viratyosin/fbsource/fbcode/hphp/test/slow/hashbang_double.php
	Exception: Failed to parse tree for path `/data/users/viratyosin/fbsource/fbcode/hphp/test/slow/hashbang_double.php`
Skipping file due to a parse exception
	Path: /data/users/viratyosin/fbsource/fbcode/hphp/test/slow/sanity/4.php
	Exception: Failed to parse tree for path `/data/users/viratyosin/fbsource/fbcode/hphp/test/slow/sanity/4.php`
Skipping file due to a parse exception
	Path: /data/users/viratyosin/fbsource/fbcode/hphp/test/slow/parser/xhp-ambiguity.php
	Exception: Failed to parse tree for path `/data/users/viratyosin/fbsource/fbcode/hphp/test/slow/parser/xhp-ambiguity.php`
Skipping file due to an exception.
	Path: /data/users/viratyosin/fbsource/fbcode/hphp/test/slow/sanity/3.php
	Exception: HH\Lib\C\firstx: Expected at least one element.
```

Manual change to remove pound comment test in `hphp/test/slow/parser/extension/shape_type_alias.php`
Manual change to update hashes in ext_factparse tests jthemphill

Reviewed By: dneiter

Differential Revision: D24457517

fbshipit-source-id: cad2124c683c6e0571df312f4a266285631f42f8