Upgrade clap, clap_completion
Summary:
This Clap update adds some new checks in `debug_asserts` that triggers new test failures in some existing CLIs (that I know of, we'll see if there's more red signals before landing). This diff fixes those along with the upgrade itself. Failure looks like this:

```
thread 'main' panicked at 'Command : Argument group 'multirepos' conflicts with non-existent 'repo' id', third-party/rust/vendor/clap_builder-4.2.7/src/builder/debug_asserts.rs:317:13
```

More context:
* https://github.com/clap-rs/clap/blob/master/clap_builder/src/builder/debug_asserts.rs#L317
* https://github.com/clap-rs/clap/commit/185729a7dc5043f75e3759e8e976183076dd50bd

First added in Clap 4.2.5.

Reviewed By: zertosh

Differential Revision: D46934728

fbshipit-source-id: 2d17c2b02fb88af04ff65a0ea35a2be171acce31