Unset -fno-operator-names for Folly/boost compat
folly/hash/Checksum.cpp includes boost/crc.hpp, which contains
alternative operator representations on Boost < 1.84.0.
This causes compilation failures when superproject CXXFLAGS are
forwarded to Folly, since we set -fno-operator-names:

```
In file included from /hhvm/third-party/folly/src/folly/hash/Checksum.cpp:22:
/hhvm/_build/third-party/boost/bundled_boost-prefix/include/boost/crc.hpp:678:68: error: use of undeclared identifier 'not'
  678 |         new_dividend_bits = reflect_optionally( new_dividend_bits, not reflect,
      |                                                                    ^
/hhvm/_build/third-party/boost/bundled_boost-prefix/include/boost/crc.hpp:670:24: warning: unused parameter 'reflect' [-Wunused-parameter]
  670 |      word_length, bool reflect )
```

As a fix, unset this compiler flag, since we have no control over the
operator representations that third-party headers might choose to use.