Fix HHBBC index.cpp compilation with newer stdlibs (#9693)
Summary:
`std::atomic` is not move-insertable, causing errors with `shrink_to_fit`:
```
In file included from /home/mszabo/hhvm/hphp/hhbbc/index.cpp:16:
In file included from /home/mszabo/hhvm/hphp/hhbbc/index.h:18:
In file included from /usr/lib/llvm-20/bin/../include/c++/v1/memory:947:
In file included from /usr/lib/llvm-20/bin/../include/c++/v1/__memory/inout_ptr.h:16:
In file included from /usr/lib/llvm-20/bin/../include/c++/v1/__memory/shared_ptr.h:34:
/usr/lib/llvm-20/bin/../include/c++/v1/__memory/uninitialized_algorithms.h:623:17: error: static assertion failed due to requirement '__is_cpp17_move_insertable<std::allocator<std::atomic<unsigned long>>, void>::value': The specified type does not meet the requirements of Cpp17MoveInsertable
  623 |   static_assert(__is_cpp17_move_insertable<_Alloc>::value,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/llvm-20/bin/../include/c++/v1/__vector/vector.h:831:8: note: in instantiation of function template specialization 'std::__uninitialized_allocator_relocate<std::allocator<std::atomic<unsigned long>>, std::atomic<unsigned long> *>' requested here
  831 |   std::__uninitialized_allocator_relocate(
      |        ^
/usr/lib/llvm-20/bin/../include/c++/v1/__vector/vector.h:1102:9: note: in instantiation of member function 'std::vector<std::atomic<unsigned long>>::__swap_out_circular_buffer' requested here
 1102 |         __swap_out_circular_buffer(__v);
      |         ^
/home/mszabo/hhvm/hphp/hhbbc/index.cpp:17351:14: note: in instantiation of member function 'std::vector<std::atomic<unsigned long>>::shrink_to_fit' requested here
 17351 |   capacities.shrink_to_fit();
       |              ^
In file included from /home/mszabo/hhvm/hphp/hhbbc/index.cpp:16:
In file included from /home/mszabo/hhvm/hphp/hhbbc/index.h:18:
In file included from /usr/lib/llvm-20/bin/../include/c++/v1/memory:943:
In file included from /usr/lib/llvm-20/bin/../include/c++/v1/__memory/allocator.h:17:
In file included from /usr/lib/llvm-20/bin/../include/c++/v1/__memory/allocate_at_least.h:14:
/usr/lib/llvm-20/bin/../include/c++/v1/__memory/allocator_traits.h:318:5: error: no matching function for call to '__construct_at'
  318 |     std::__construct_at(__p, std::forward<_Args>(__args)...);
      |     ^~~~~~~~~~~~~~~~~~~
/usr/lib/llvm-20/bin/../include/c++/v1/__memory/uninitialized_algorithms.h:634:33: note: in instantiation of function template specialization 'std::allocator_traits<std::allocator<std::atomic<unsigned long>>>::construct<std::atomic<unsigned long>, std::atomic<unsigned long>, void, 0>' requested here
  634 |       allocator_traits<_Alloc>::construct(__alloc, std::__to_address(__result), std::move_if_noexcept(*__iter));
      |                                 ^
/usr/lib/llvm-20/bin/../include/c++/v1/__vector/vector.h:831:8: note: in instantiation of function template specialization 'std::__uninitialized_allocator_relocate<std::allocator<std::atomic<unsigned long>>, std::atomic<unsigned long> *>' requested here
  831 |   std::__uninitialized_allocator_relocate(
      |        ^
/usr/lib/llvm-20/bin/../include/c++/v1/__vector/vector.h:1102:9: note: in instantiation of member function 'std::vector<std::atomic<unsigned long>>::__swap_out_circular_buffer' requested here
 1102 |         __swap_out_circular_buffer(__v);
      |         ^
/home/mszabo/hhvm/hphp/hhbbc/index.cpp:17351:14: note: in instantiation of member function 'std::vector<std::atomic<unsigned long>>::shrink_to_fit' requested here
 17351 |   capacities.shrink_to_fit();
       |              ^
/usr/lib/llvm-20/bin/../include/c++/v1/__memory/construct_at.h:46:58: note: candidate template ignored: substitution failure [with _Tp = std::atomic<unsigned long>, _Args = <std::atomic<unsigned long>>]: call to implicitly-deleted copy constructor of 'std::atomic<unsigned long>'
   45 | template <class _Tp, class... _Args, class = decltype(::new(std::declval<void*>()) _Tp(std::declval<_Args>()...))>
      |                                                                                    ~~~
   46 | _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR_SINCE_CXX20 _Tp* __construct_at(_Tp* __location, _Args&&... __args) {
      |
```

Also add an explicit `<fstream>` include as it's no longer included transitively.

Pull Request resolved: https://github.com/facebook/hhvm/pull/9693

Reviewed By: ricklavoie

Differential Revision: D89285910

fbshipit-source-id: b36b9707368e8cca1dd664e89f68b414e6ac21ab