fix clean mac builds by making ppc64-asm depend on hphp_util
Summary:
If you have a completely clean system, the build will fail sometimes,
depending on the undefined order in which CMake will build targets if there is
not an explicit relationship.

This happens to mean that ppc64-asm gets built very early on Macs.

refs hhvm/homebrew-hhvm#115

After
https://github.com/facebook/hhvm/commit/86af7d59acfa3308b0bbfec81dfb017bff117eee
, everything that depends on `runtime-option.h` now depends on
`hphp/util/low-ptr-def.h`

```
In file included from hphp/ppc64-asm/asm-ppc64.cpp:20:
In file included from hphp/runtime/base/runtime-option.h:33:
In file included from hphp/runtime/base/typed-value.h:21:
In file included from hphp/runtime/vm/class-meth-data-ref.h:19:
In file included from hphp/runtime/vm/class-meth-data.h:19:
In file included from hphp/runtime/base/countable.h:21:
hphp/util/alloc.h:31:10: fatal error: 'hphp/util/low-ptr-def.h' file not found
```

Explicitly add this dependency so CMake builds things in the right order.

Probably not found by legocastle due to different CMake versions, and the build
order being undefined.

Reviewed By: markw65

Differential Revision: D14243063

fbshipit-source-id: ee94ee0961d14ee1fe159a78b61646aefae81d96