Fix protocol id error format
Summary:
Stumbled upon this while writing an unrelated unittest:
```
=== RUN   TestClient
2024/11/13 11:44:34 read first frame failed: read first frame failed: EOF
    client_options_test.go:93: expected to get an error when creating client: Unknown protocol id: 0x756e6b6e6f776e
 --- FAIL: TestClient (0.00s)
```

No need to use hexadecimal notation, since Protocol IDs are small decimal numbers:
https://www.internalfb.com/code/fbsource/[959c747a3968]/fbcode/thrift/lib/go/thrift/types/format.go?lines=27-34

Reviewed By: awalterschulze

Differential Revision: D65900201

fbshipit-source-id: 05da2057b843686bcb208843fd9240e2bbdc1edd