fix test_abnormal_typechecker_exit_message
Summary:
This test has been broken for ages (at least since October 2018).

You invoke `buck test mode/dbg hphp/hack/test/integration:integration_test_fresh_init`. This invokes in common_tests.py the line `self.check_cmd(...,assert_loaded_saved_state=False)`. But it dispatches to the definition of check_cmd in test_fresh_init.py, which lacks a parameter named "assert_loaded_saved_state", and so fails:

```
======================================================================
ERROR: test_abnormal_typechecker_exit_message (hphp.hack.test.integration.test_fresh_init.TestFreshInit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "common_tests.py", line 774, in test_abnormal_typechecker_exit_message
TypeError: check_cmd() got an unexpected keyword argument 'assert_loaded_mini_state'
```

(this failure actually dates back from October 9th 2018 when the parameter was named "assert_loaded_mini_state"; since then the parameter was renamed to "assert_loaded_saved_state" so it now gives an error about that).

This fix supports two scenarios:

1. When you invoke the test_fresh_init runner and it calls common_tests.py:test_abnormal_typechecker_exit_message then its call to `check_cmd(assert_loaded_saved_state=False)` will invoke test_fresh_init.py:check_cmd and the argument will match the dummy parameter newly introduced by this diff
2. When you invoke the integration_saved_state runner and it calls common_tests.py:test_abnormal_typechecker_exit_message then its call to `check_cmd(assert_loaded_saved_state=False)` will invoke a different check_cmd, one which really does use the argument.

Overall, I'm not happy that we use so many layers of indirection in these tests. I wish they were a lot less clever.

Reviewed By: 2BitSalute

Differential Revision: D13858395

fbshipit-source-id: e739848752d5fd8e4d8e1fbe5184883b86c5c2fd