Fix looping behavior when type constants have multiple upper bounds
Summary:
When a lambda returns a type involving an expression-dependent type constant whose bounds reference itself, the `hh` will enter an infinite loop and eventually timeout, e.g.:

```hack
<<file:__EnableUnstableFeatures('type_const_multiple_bounds')>>

interface IBase {}
interface ICreatable<+TEnt as IBase> {
  public function get(): TEnt;
}
abstract class Builder {
  abstract const type TEnt as IBase as ICreatable<this::TEnt>;
  public function getTEnt(): this::TEnt { throw new Exception('stub'); }
}
function use_builder(Builder $b): void {
  $fn = (Builder $b2) ==> $b2->getTEnt();
  $fn($b);
}
```

```
error: Typing[4361] Encountered an internal compiler error while typechecking this. Addressing other errors, restarting the typechecker with hh restart, or rebasing might resolve this error. Please run hh rage and post in https://fb.workplace.com/groups/hackforhiphop/. [1]
```

The loop happens in the `typing_escape.ml` code. After typechecking a lambda, any "rigid" type variables (corresponding to unpacked existentials) created inside it (expression-dependent types, type parameters from `is` refinements) must not escape into the outer continuation.

`refresh_env_and_type` walks the return type and all local variable types, looking for rigid generics that were added to the `tpenv` compare to a snapshot of the environment taken before the typing of the lambda.

When it finds one, it applies 'exposure' and `eliminate` replaces it according to variance: in covariant position, replace with the intersection of upper bounds; in contravariant position, replace with the union of lower bounds.

After eliminating a generic, `eliminate` calls `refresh_type` on the resulting bound to transitively eliminate any other escaping generics that appear within it. This `eliminate`/`refresh_type` mutual recursion is how nested escaping types are handled.

For `<expr#N>::TEnt` with upper bound `IBase & ICreatable<\<expr#N>::TEnt>`, `eliminate` replaces the generic with its upper bounds, then `refresh_type` recurses into he bound. Inside `ICreatable<...>`, it finds the same generic `<expr#N>::TEnt`, calls `eliminate` again, which produces the same bounds, and the cycle repeats.

The fix adds an a new fields to `renv` to track which generics are currently being eliminated. Before calling `eliminate`, we check whether the generic is already in the set; if so, we keep it unchanged, breaking the cycle. This does not change behavior in non-cyclic cases.

Reviewed By: andrewjkennedy

Differential Revision: D94354375

fbshipit-source-id: 315f8774c05e89539006663ebea8698f0a36e6b3