add missing include in ext_stream
Summary: We need to include sys/stat.h, or we might get errors such as:
error: aggregate 'stat s' has incomplete type and cannot be defined

Fixes the OSX build.
Closes #3061

Reviewed By: @fredemmott

Differential Revision: D1410257

Pulled By: @LiraNuna