Convert remaining hhas tests to hack tests
Summary:
Convert remaining hhas tests to hack tests
- cgets.hhas is the same test as class_get.php
- For SetS, anything of the form:
```
class Foo {
   public static Bar $c;
}
Foo::$c = readonly new Bar();
```
reports the HackC error
```
Fatal error: This expression is readonly, but the collection you're modifying is mutable, which isn't allowed.
```
jamesjwu is there a case HackC wouldn't catch us setting a mutable static property with a readonly value?

I also think we need to leave the allow_hhas=1 in there for the bytecode verification tests.

Reviewed By: oulgen

Differential Revision: D30929075

fbshipit-source-id: e288194102851cf4f635df79bd039ce2fc7c5349