Forbidding 'async' annotation on abstract methods
Summary:
This diff fixes the issue raised in S148539 and T19641441. Specifically:

Prior to this diff, the full fidelity and original parsers would throw no errors on methods declared both 'abstract' and 'async', even though the HHVM would reject such code at run time. For example, both parsers accepted the code in test_async_errors.php, even though HHVM would throw errors on lines 5, 11, and 17, reproduced below:

Fatal error: Cannot declare interface method I::i2() async; async is only meaningful when it modifies a method body ... on line 5.

Fatal error: Cannot declare abstract method C::c3() async; async is only meaningful when it modifies a method body ... on line 11.

Fatal error: Cannot declare abstract method T::t3() async; async is only meaningful when it modifies a method body ... on line 17.

In this diff, I've added error2046 to the full fidelity parser, ensuring that HHVM and the full fidelity parser agree on disallowing 'async' annotations on 'abstract' methods. Since HHVM didn't specify a specific location for the error--just a line number--I chose to put the error on the 'async' annotation.

Also, I realize that the error message suggests the 'Awaitable<...>' return type annotation even if such an annotation is already present. My intuition is that this is still fine for nudging the reader in the right direction, but I'd love to hear other thoughts.

Reviewed By: ericlippert

Differential Revision: D5349131

fbshipit-source-id: c58270ef43ab4bfded9a8c1b13e1bd5900525191