Fix compiler_failure_test on windows
Summary:
All compiler failure tests are failing on Windows because of newline mismatch, e.g.

```
AssertionError: '[ERR[43 chars]n field `field1` is only allowed in the experimental mode.\r
' != '[ERR[43 chars]n field `field1` is only allowed in the experimental mode.
'
- [ERROR:foo.thrift:6] Using thrift.TerseWrite on field `field1` is only allowed in the experimental mode.
?                                                                                                          -
+ [ERROR:foo.thrift:6] Using thrift.TerseWrite on field `field1` is only allowed in the experimental mode.
```

Fix it.

Reviewed By: Mizuchi

Differential Revision: D46129518

fbshipit-source-id: 12171f6a153a3d2043f8a303c6519f5620a38c25