Fix buck2 build error in xplat/thrift (#9355)
Summary:
Pull Request resolved: https://github.com/facebook/hhvm/pull/9355

X-link: https://github.com/facebook/fbthrift/pull/546

Error
```
[2023-04-03T10:54:13.480-07:00] Stderr: xplat/thrift/lib/cpp/test/Base64Test.cpp:37:6: error: no previous prototype for function 'checkEncoding' [-Werror,-Wmissing-prototypes]
[2023-04-03T10:54:13.480-07:00] void checkEncoding(uint8_t* data, int len) {
[2023-04-03T10:54:13.480-07:00]      ^' in /var/sandcastle/deployment/mount/53446/flib/intern/sandcastle/core/shell/SandcastleStatusDecoderBase.php:279
```

This function needs to be static for it to be considered a prototype

Reviewed By: kkolur76

Differential Revision: D44649127

fbshipit-source-id: 580995d3b806fd84dabb3cca85e866d15f1531be