Solve hack compilation issues on ppc64 platform
It used to work, but since february I started having this:
```
$ cd hphp/hack
$ make
Finished, 16 targets (16 cached) in 00:00:00.
+ /usr/bin/ocamlc.opt -c -g -w A -warn-error A -w -27 -w -3-4-6-29-35-44-48-50 -I utils -I typing -I search -I watchman -I procs -I deps -I stubs -I h2tp -I naming -I dfind -I socket -I libancillary -I hhi -I fsnotify_linux -I server -I hh_matcher -I find -I parsing -I heap -I globals -I format -I monitor -I decl -I emitter -I client -I h2tp/unparser -I h2tp/mapper -I h2tp/common -I utils/collections -I utils/hh_json -I hh_matcher/test -I third-party/inotify -I third-party/core -I third-party/avl -o utils/exit_status.cmo utils/exit_status.ml
File "utils/exit_status.ml", line 52, characters 4-6:
Warning 41: Ok belongs to several types: t result
The first one was selected. Please disambiguate if this is wrong.
File "utils/exit_status.ml", line 94, characters 4-6:
Warning 41: Ok belongs to several types: t result
The first one was selected. Please disambiguate if this is wrong.
File "utils/exit_status.ml", line 1:
Error: Some fatal warnings were triggered (2 occurrences)
Command exited with code 2.
Compilation unsuccessful after building 89 targets (59 cached) in 00:00:01.
Makefile:149: recipe for target '_build/hh_server.native' failed
make[3]: *** [_build/hh_server.native] Error 10
hphp/hack/CMakeFiles/hack.dir/build.make:49: recipe for target 'hphp/hack/CMakeFiles/hack' failed
make[2]: *** [hphp/hack/CMakeFiles/hack] Error 2
CMakeFiles/Makefile2:1525: recipe for target 'hphp/hack/CMakeFiles/hack.dir/all' failed
make[1]: *** [hphp/hack/CMakeFiles/hack.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
```

So I removed that warning from error and tried again:
```
$ make
Finished, 16 targets (16 cached) in 00:00:00.
+ /usr/bin/ocamlopt.opt -c -g -w A -warn-error A -w -27 -w -3-4-6-29-35-41-44-48-50 -I server -I typing -I search -I watchman -I procs -I deps -I stubs -I h2tp -I naming -I dfind -I socket -I libancillary -I utils -I hhi -I fsnotify_linux -I hh_matcher -I find -I parsing -I heap -I globals -I format -I monitor -I decl -I emitter -I client -I h2tp/unparser -I h2tp/mapper -I h2tp/common -I utils/collections -I utils/hh_json -I hh_matcher/test -I third-party/inotify -I third-party/core -I third-party/avl -o server/ideJsonUtils.cmx server/ideJsonUtils.ml
File "server/ideJsonUtils.ml", line 24, characters 15-30:
Warning 52: the argument of this constructor should not be matched against a
constant pattern; the actual value of the argument could change
in the future
File "server/ideJsonUtils.ml", line 14, characters 0-11:
Warning 45: this open statement shadows the constructor Ok (which is later used)
File "server/ideJsonUtils.ml", line 14, characters 0-11:
Warning 45: this open statement shadows the constructor Error (which is later used)
File "server/ideJsonUtils.ml", line 1:
Error: Some fatal warnings were triggered (3 occurrences)
Command exited with code 2.
Compilation unsuccessful after building 721 targets (36 cached) in 00:00:29.
Makefile:149: recipe for target '_build/hh_server.native' failed
make[3]: *** [_build/hh_server.native] Error 10
hphp/hack/CMakeFiles/hack.dir/build.make:49: recipe for target 'hphp/hack/CMakeFiles/hack' failed
make[2]: *** [hphp/hack/CMakeFiles/hack] Error 2
CMakeFiles/Makefile2:1525: recipe for target 'hphp/hack/CMakeFiles/hack.dir/all' failed
make[1]: *** [hphp/hack/CMakeFiles/hack.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
```

Only after that it worked:
```
$ make
Finished, 16 targets (16 cached) in 00:00:00.
Finished, 1084 targets (284 cached) in 00:00:47.
Built target hack
```

Tested with ocaml trunk dde64243bf38c75f0e24e6487eab6f3e6e85dd14