some codepaths ignore www parameter
Summary:
Repro:
```
$ cd /tmp
$ hh stop ~/www
<Modify any decl, e.g. in EntEmployee.php comment out on of the "implements">
$ hh ~/www
```
This ends up with hh in an infinite crash loop, here:
```
Error: could not find a .hhconfig file in /data/users/ljw/fbsource/fbcode/hphp/hack or any of its parent directories. Do you have a .hhconfig in your code's root directory?
src/utils/wwwroot.ml @ 31
src/utils/wwwroot.ml @ 59
src/decl/remote_old_decl_client.ml @ 16
src/decl/remote_old_decl_client.ml @ 125
src/providers/shallow_classes_provider.ml @ 130
src/decl/shallow_decl_compare.ml @ 38
```

The problem is that the old decl service simply doesn't pass the command-line root argument, i.e. it assumes the current directory is within WWW.

This diff doesn't fix it. It's solely a rename+refactor so the API "Www.getroot" is now more dangerously named, to avoid more places cropping up in future. I added "TODO" comments to the four places in the code which I think are bugs.

Reviewed By: bobrenjc93

Differential Revision: D44369977

fbshipit-source-id: 8820ec97457c583a2db89edb94f9bbc3df85ca2d