fix(oss): Make ExceptionWrapper explicitly formattable
Summary:
In OSS, glog + fmt requires enum classes to be explicitly formattable. (Internal tooling automagically does this.)

This fixes a build error in the OSS build of sapling:
```
| In file included from /tmp/fbcode_builder_getdeps-ZUsersZbenZossZsaplingZbuildZfbcode_builder-root/installed/fmt-D8kIIbuH_WwNugCsuzfJISa4iK0ETp73FQx_CYqwA_s/include/fmt/format.h:41,
|                  from /tmp/fbcode_builder_getdeps-ZUsersZbenZossZsaplingZbuildZfbcode_builder-root/installed/folly/include/folly/lang/Exception.h:27,
|                  from /tmp/fbcode_builder_getdeps-ZUsersZbenZossZsaplingZbuildZfbcode_builder-root/installed/folly/include/folly/Optional.h:74,
|                  from /tmp/fbcode_builder_getdeps-ZUsersZbenZossZsaplingZbuildZfbcode_builder-root/installed/folly/include/folly/futures/Future.h:27,
|                  from /tmp/fbcode_builder_getdeps-ZUsersZbenZossZsaplingZbuildZfbcode_builder-root/installed/edencommon/include/eden/common/utils/ImmediateFuture.h:10,
|                  from /Users/ben/oss/sapling/eden/fs/inodes/CheckoutAction.h:13,
|                  from /Users/ben/oss/sapling/eden/fs/inodes/CheckoutAction.cpp:8:
| /tmp/fbcode_builder_getdeps-ZUsersZbenZossZsaplingZbuildZfbcode_builder-root/installed/fmt-D8kIIbuH_WwNugCsuzfJISa4iK0ETp73FQx_CYqwA_s/include/fmt/base.h: In instantiation of ‘constexpr fmt::v11::detail::value<Context> fmt::v11::detail::make_arg(T&) [with bool PACKED = true; Context = fmt::v11::context; T = const folly::exception_wrapper; typename std::enable_if<PACKED, int>::type <anonymous> = 0]’:
| /tmp/fbcode_builder_getdeps-ZUsersZbenZossZsaplingZbuildZfbcode_builder-root/installed/fmt-D8kIIbuH_WwNugCsuzfJISa4iK0ETp73FQx_CYqwA_s/include/fmt/base.h:2018:74:   required from ‘constexpr fmt::v11::detail::format_arg_store<Context, NUM_ARGS, 0, DESC> fmt::v11::make_format_args(T& ...) [with Context = fmt::v11::context; T = {const folly::Range<const char*>, const folly::exception_wrapper}; long unsigned int NUM_ARGS = 2; long unsigned int NUM_NAMED_ARGS = 0; long long unsigned int DESC = 253; typename std::enable_if<(NUM_NAMED_ARGS == 0), int>::type <anonymous> = 0]’
| /tmp/fbcode_builder_getdeps-ZUsersZbenZossZsaplingZbuildZfbcode_builder-root/installed/folly/include/folly/logging/LogStreamProcessor.h:371:52:   required from ‘std::string folly::LogStreamProcessor::formatLogString(folly::StringPiece, const Args& ...) [with Args = {folly::Range<const char*>, folly::exception_wrapper}; std::string = std::__cxx11::basic_string<char>; folly::StringPiece = folly::Range<const char*>]’
| /tmp/fbcode_builder_getdeps-ZUsersZbenZossZsaplingZbuildZfbcode_builder-root/installed/folly/include/folly/logging/LogStreamProcessor.h:255:28:   required from ‘folly::LogStreamProcessor::LogStreamProcessor(folly::XlogFileScopeInfo*, folly::LogLevel, folly::StringPiece, bool, folly::StringPiece, unsigned int, folly::StringPiece, folly::LogStreamProcessor::FormatType, folly::StringPiece, Args&& ...) [with Args = {folly::Range<const char*>&, folly::exception_wrapper&}; folly::StringPiece = folly::Range<const char*>]’
| /Users/ben/oss/sapling/eden/fs/inodes/CheckoutAction.cpp:190:3:   required from here
| /tmp/fbcode_builder_getdeps-ZUsersZbenZossZsaplingZbuildZfbcode_builder-root/installed/fmt-D8kIIbuH_WwNugCsuzfJISa4iK0ETp73FQx_CYqwA_s/include/fmt/base.h:1641:63: error: ‘fmt::v11::detail::type_is_unformattable_for<const folly::exception_wrapper, char> _’ has incomplete type
|  1641 |     type_is_unformattable_for<T, typename Context::char_type> _;
|       |                                                               ^
| /tmp/fbcode_builder_getdeps-ZUsersZbenZossZsaplingZbuildZfbcode_builder-root/installed/fmt-D8kIIbuH_WwNugCsuzfJISa4iK0ETp73FQx_CYqwA_s/include/fmt/base.h:1644:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
|  1644 |       formattable,
|       |       ^~~~~~~~~~~
| /tmp/fbcode_builder_getdeps-ZUsersZbenZossZsaplingZbuildZfbcode_builder-root/installed/fmt-D8kIIbuH_WwNugCsuzfJISa4iK0ETp73FQx_CYqwA_s/include/fmt/base.h:1644:7: note: ‘formattable’ evaluates to false
```

X-link: https://github.com/facebook/folly/pull/2506

Reviewed By: yfeldblum

Differential Revision: D82664859

Pulled By: genevievehelsel

fbshipit-source-id: 47274cda0e42ea861b481c61f0be2da00d32e08f