Clownlist doctrine2 test that also fails on php5
Summary: refs facebook/hhvm#3375

```
Exception: [Doctrine\Common\Proxy\Exception\OutOfBoundsException] Missing value for primary key id on Doctrine\Tests\Models\CMS\CmsUser

With queries:
18. SQL: '"COMMIT"' Params:
17. SQL: 'INSERT INTO cms_users (status, username, name, email_id) VALUES (?, ?, ?, ?)' Params: '', 'ocramius', 'Marco', ''
16. SQL: '"START TRANSACTION"' Params:
15. SQL: 'CREATE TABLE cms_groups (id INTEGER NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY(id))' Params:
14. SQL: 'CREATE TABLE cms_emails (id INTEGER NOT NULL, email VARCHAR(250) NOT NULL, PRIMARY KEY(id))' Params:
13. SQL: 'CREATE UNIQUE INDEX UNIQ_ACAC157BA76ED395 ON cms_addresses (user_id)' Params:
12. SQL: 'CREATE TABLE cms_addresses (id INTEGER NOT NULL, user_id INTEGER DEFAULT NULL, country VARCHAR(50) NOT NULL, zip VARCHAR(50) NOT NULL, city VARCHAR(50) NOT NULL, PRIMARY KEY(id), CONSTRAINT FK_ACAC157BA76ED395 FOREIGN KEY (user_id) REFERENCES cms_users (id) NOT DEFERRABLE INITIALLY IMMEDIATE)' Params:
11. SQL: 'CREATE INDEX IDX_D533FD95A76ED395 ON cms_articles (user_id)' Params:
10. SQL: 'CREATE TABLE cms_articles (id INTEGER NOT NULL, user_id INTEGER DEFAULT NULL, topic VARCHAR(255) NOT NULL, text CLOB NOT NULL, version INTEGER DEFAULT 1 NOT NULL, PRIMARY KEY(id), CONSTRAINT FK_D533FD95A76ED395 FOREIGN KEY (user_id) REFERENCES cms_users (id) NOT DEFERRABLE INITIALLY IMMEDIATE)' Params:
9. SQL: 'CREATE INDEX IDX_F21F790FA76ED395 ON cms_phonenumbers (user_id)' Params:
8. SQL: 'CREATE TABLE cms_phonenumbers (phonenumber VARCHAR(50) NOT NULL, user_id INTEGER DEFAULT NULL, PRIMARY KEY(phonenumber), CONSTRAINT FK_F21F790FA76ED395 FOREIGN KEY (user_id) REFERENCES cms_users (id) NOT DEFERRABLE INITIALLY IMMEDIATE)' Params:
7. SQL: 'CREATE INDEX IDX_7EA9409AFE54D947 ON cms_users_groups (group_id)' Params:
6. SQL: 'CREATE INDEX IDX_7EA9409AA76ED395 ON cms_users_groups (user_id)' Params:
5. SQL: 'CREATE TABLE cms_users_groups (user_id INTEGER NOT NULL, group_id INTEGER NOT NULL, PRIMARY KEY(user_id, group_id), CONSTRAINT FK_7EA9409AA76ED395 FOREIGN KEY (user_id) REFERENCES cms_users (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_7EA9409AFE54D947 FOREIGN KEY (group_id) REFERENCES cms_groups (id) NOT DEFERRABLE INITIALLY IMMEDIATE)' Params:
4. SQL: 'CREATE UNIQUE INDEX UNIQ_3AF03EC5A832C1C9 ON cms_users (email_id)' Params:
3. SQL: 'CREATE UNIQUE INDEX UNIQ_3AF03EC5F85E0677 ON cms_users (username)' Params:
2. SQL: 'CREATE TABLE cms_users (id INTEGER NOT NULL, email_id INTEGER DEFAULT NULL, status VARCHAR(50) DEFAULT NULL, username VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id), CONSTRAINT FK_3AF03EC5A832C1C9 FOREIGN KEY (email_id) REFERENCES cms_emails (id) NOT DEFERRABLE INITIALLY IMMEDIATE)' Params:
```

Reviewed By: @JoelMarcey

Differential Revision: D1482260