Remove redundant generics in Syntax* & *SmartConstructors
Summary:
Turn type parameters `Token` and `Value` in `SyntaxType` into associated types,
as they caused an *avalanche effect* whenever used generically. E.g., old code
    impl<S: SyntaxType<Token, Value>, Token, Value>
    SomeSmartConstructors<S, Token, Value>
    where
        Token: LexableToken,
        Value: SyntaxValueType<Token>
now becomes as simple (and readable) as:
    impl<S: SyntaxType> SomeSmartConstructors<S>
and most importantly, the where-clause *no longer* needs to be **duplicated**
across the type hierarchy of traits, so the code is more maintanable.
___

(The remaining type parameter `S` in `SyntaxSmartConstructors` is indeed
necessary; attempting a rewrite by refining the type bound on `R`, i.e.:
    pub trait SyntaxSmartConstructors<'a, State = NoState>:
        SmartConstructors<'a, State::T>
    where
        State: StateType<'a, <Self as SmartConstructors<'a, State::T>>::R>,
        <Self as SmartConstructors<'a, State::T>>::R: SyntaxType,
reports the following:
```
error[E0391]: cycle detected when computing the bounds for type parameter `State`
  --> hphp/hack/src/parser/syntax_smart_constructors.rs:27:57
   |
27 |     State: StateType<'a, <Self as SmartConstructors<'a, State::T>>::R>,
   |                                                         ^^^^^^^^
   |
   = note: ...which again requires computing the bounds for type parameter `State`, completing the cycle
note: cycle used when computing the supertraits of `syntax_smart_constructors::SyntaxSmartConstructors`
  --> hphp/hack/src/parser/syntax_smart_constructors.rs:25:27
   |
25 |     SmartConstructors<'a, State::T>
   |                           ^^^^^^^^
```
)

Reviewed By: dabek

Differential Revision: D15214494

fbshipit-source-id: de935929dbad6ea39917799f25a944d7ec8ddd8a