Fix casting of array data to specialized types
Summary:
Two upstream changes in LLDB affected our scripts:
## 1)
The cast in [these lines](https://www.internalfb.com/code/fbsource/[964a2c5725942a99540b9173b9847e4356478434]/fbcode/hphp/tools/lldb/utils.py?lines=833%2C835) started failing. The error for that bad cast is only visible when you call `array_data.GetError()`:
```
>>> array_data.IsValid()
True
>>> array_data.GetError()
error: Can only cast to a type that is equal to or smaller than the orignal type.
```

It looks like this functionality was broken (but I guess I should say technically fixed) in an upstream LLDB commit a few weeks ago: https://reviews.llvm.org/D153657 (synced internally here: https://www.internalfb.com/phabricator/commit/OMEXTLLVMPROJECT/f05e2fb013f0e2504471a9899dba7d70cc58a63d)

## 2)
The pretty printing of references (i.e. it was printing contents of references when it shouldn't have) was fixed in https://reviews.llvm.org/D152409. So a test case needed to be updated here.

Reviewed By: jtwarren

Differential Revision: D47687403

fbshipit-source-id: d557a57e1dc384aebbf81dc862cdfa4760ded7c2