Add clap TypedValueParser implementation for Thrift enums
Summary:
Clap uses a cascade of trait impls to decide how to parse an argument such as this:

```lang=rust
#[derive(Parser, Debug)]
struct Args {
    #[arg(long)]
    logical_server_type: Option<LogicalServerType>,
}
```

The first one of the following traits that is implemented on `LogicalServerType` determines how the command-line flag gets parsed:

1. `clap::builder::ValueParserFactory`
2. `clap::ValueEnum`
3. `From<std::ffi::OsString>`
4. `for<'a> From<&'a std::ffI::OsStr>`
5. `From<String>`
6. `for<'a> From<&'a str>`
7. `std::str::FromStr`

Among these, Thrift enums previously implemented only `FromStr`. The `FromStr`-based parsing implementation does not respect `ignore_case = true`.

Applications that wanted case-insensitive parsing of a Thrift enum had to accomplish it using something like this, with 3 repetitions of the type name `LogicalServerType` that would cause runtime crashes if they were out of sync from a copy-paste error:

```lang=rust
use clap::builder::PossibleValuesParser;
use clap::builder::TypedValueParser as _;
use fbthrift::ThriftEnum as _;

#[derive(Parser, Debug)]
struct Args {
    #[arg(
        long,
        value_parser = PossibleValuesParser::new(LogicalServerType::variants())
            .map(|input| {
                LogicalServerType::enumerate()
                    .iter()
                    .find_map(|&(variant, name)| input.eq_ignore_ascii_case(name).then_some(variant))
                    .unwrap()
            }),
        ignore_case = true,
    )]
    logical_server_type: Option<LogicalServerType>,
}
```

This diff adds a dedicated `TypedValueParser` for Thrift enums and wires it up automatically using `ValueParserFactory`, which provides 2 advantages:

- Flags are automatically parsed in a way that respects `ignore_case = true` in the #[arg(...)] attribute.

```lang=rust
#[derive(Parser, Debug)]
struct Args {
    #[arg(long, ignore_case = true)]
    logical_server_type: Option<LogicalServerType>,
}
```

- When passed a value which is not a valid variant of the Thrift enum, the help message will show the correct possible values.

```lang=log
error: invalid value 'wt0' for '--logical-server-type <LOGICAL_SERVER_TYPE>'
  [possible values: UNKNOWN, T1, T2, T3, T3_1P, T3_2P, T4, T5, T6, T6F, T6M, T7, T8, T9, T10, T10N, T11, T15, T16, T17, T20, T21, T22, T23, T23C, T23K, T23A, TNG, TNM, TEXP, TE1, TE16, TE20, EE_VM, EE_VM_1P, EE_VM_2P]

For more information, try '--help'.
```

Enum variant values will also appear in `--help`. This can be suppressed with `hide_possible_values = true`.

```lang=rust
#[derive(Parser, Debug)]
struct Args {
    #[arg(long, hide_possible_values = true)]
    logical_server_type: Option<LogicalServerType>,
}
```

Reviewed By: diliop

Differential Revision: D103623055

fbshipit-source-id: bb1eec07fe35b31af15b81ed028b0801dc2c055f