fix cargo_vendor.sh --facebook
Summary:
Not sure if `cargo_vendor.sh --facebook` is still being used (first introduced in D27850753 (https://github.com/facebook/hhvm/commit/d371b7d2a72a4d0fa1b0d3ed70f5e9d103dfe772)), but currently it errors when run. This diff fixes the errors but I'm happy to discard the change if this is no longer relevant.

Several files listed in `.cargo/Cargo.toml.ocaml_build` have been moved or deleted. Remove them from the list.

Also seeing
```
$ scripts/facebook/cargo_vendor.sh --facebook
Updating crates.io index
error: failed to sync

Caused by:
  failed to load pkg lockfile

Caused by:
  failed to select a version for the requirement `daemonize = "^0.5"`
  candidate versions found which didn't match: 0.4.1, 0.4.0, 0.3.0, ...
  location searched: crates.io index
  required by package `hphp_hack_src_facebook_hh_decl v0.0.0 (/data/users/milliechen/fbsource/fbcode/hphp/hack/src/facebook/hh_decl)`
```
So replace the daemonize pkg with the one in third-party/rust.

Reviewed By: CatherineGasnier

Differential Revision: D34746212

fbshipit-source-id: bfc8db1e09144f9b0ed2d1815b2aaef244a9e2d6