Fix -Wshadow issue in Rust generator
Summary:
This flags on clang for Windows:
```
xplat\thrift\compiler\generate\t_mstch_rust_generator.cc(1042,24): error: declaration shadows a local variable [-Werror,-Wshadow]
        const t_const* annot =
                       ^
xplat\thrift\compiler\generate\t_mstch_rust_generator.cc(1038,24): note: previous declaration is here
        const t_const* annot =
                       ^
```
as apparently doing e.g. `if (int i = ...)` declares the variable at that outer scope, different from `for (int i; ...)`.

And this may flag on win-clang because we use stricter warning defaults there with `-Wshadow` and possibly do not do the same for Mac/Linux/Android. Let's fix the names not to conflict.

Reviewed By: shayne-fletcher

Differential Revision: D58816813

fbshipit-source-id: 27d2fbea63a0669f974c9a7d190e9003ea7aac91