Revert "Update Joomla to 3.4.1"
Summary: Does not appear to be tested. refs facebook/hhvm#5249 - brakes
run

```
ERROR: Could not disable
/data/fio/hhvm/hphp/test/frameworks/framework_downloads/joomla-cms/tests/unit/suites/libraries/cms/form/field/JFormFieldCaptchaTest.php
in joomlacms!
```

This reverts commit 7f68616de3bdb67e4df0fe637efba4ac83f1ef3f.

Reviewed By: @jwatzman