fix build error on gcc 7.5
Summary:
The OSS build of CacheLib on Ubuntu-18.04 has been broken with below errors
(https://fburl.com/pb5v5p5z)

```
cd /__w/CacheLib/CacheLib/build-fbthrift/thrift/compiler && /usr/bin/c++ -DFMT_LOCALE -DFMT_SHARED
-DTHRIFT_HAVE_LIBSNAPPY=0 -Dcompiler_EXPORTS -I/__w/CacheLib/CacheLib/cachelib/external/fbthrift/.
-I/__w/CacheLib/CacheLib/build-fbthrift -isystem /__w/CacheLib/CacheLib/opt/cachelib/include -O2 -g
-DNDEBUG -fPIC -std=c++1z -MD -MT thrift/compiler/CMakeFiles/compiler.dir/lib/rust/util.cc.o -MF
CMakeFiles/compiler.dir/lib/rust/util.cc.o.d -o CMakeFiles/compiler.dir/lib/rust/util.cc.o -c
/__w/CacheLib/CacheLib/cachelib/external/fbthrift/thrift/compiler/lib/rust/util.cc
/__w/CacheLib/CacheLib/cachelib/external/fbthrift/thrift/compiler/lib/rust/util.cc:19:10: fatal
error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [thrift/compiler/CMakeFiles/compiler.dir/lib/rust/util.cc.o] Error 1
thrift/compiler/CMakeFiles/compiler.dir/build.make:173: recipe for target
'thrift/compiler/CMakeFiles/compiler.dir/lib/rust/util.cc.o' failed
make[2]: Leaving directory '/__w/CacheLib/CacheLib/build-fbthrift'
CMakeFiles/Makefile2:332: recipe for target 'thrift/compiler/CMakeFiles/compiler.dir/all' failed
make[1]: *** [thrift/compiler/CMakeFiles/compiler.dir/all] Error 2
make[1]: Leaving directory '/__w/CacheLib/CacheLib/build-fbthrift'
Makefile:155: recipe for target 'all' failed
make: *** [all] Error 2
build-package.sh: error: make failed
Error: Process completed with exit code 1.
```

Not sure why this is happening now, but it seems that the `filesystem` was located in
`experimental/filesystem` for older gcc <= 7.5. This change fixes the compile error by guarding the
include with `_WIN32` build where the `std::filesystem` is used.

Reviewed By: emersonford

Differential Revision: D48876410

fbshipit-source-id: c5db32ee38d371f72e7998a37fd61d1b1cdfc77b