Fix errors in oxidized_regen.sh due to custom build profile
Summary:
We disabled incremental builds for OSS builds in D28343366 (https://github.com/facebook/hhvm/commit/86ed8748f0ea1d1f647ca5ee9b1ecd22ae6970c9) (this change did not affect buck builds).

We are no longer on rustc 1.52 (which had incremental compilation bugs) and overriding the profile caused a ton of warnings and one build error.

```
$ hphp/hack/src/oxidized_regen.sh
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /data/users/wilfred/fbsource/fbcode/hphp/hack/src/arena_collections/Cargo.toml
workspace: /data/users/wilfred/fbsource/fbcode/hphp/hack/Cargo.toml
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /data/users/wilfred/fbsource/fbcode/hphp/hack/src/utils/arena_deserializer/Cargo.toml
workspace: /data/users/wilfred/fbsource/fbcode/hphp/hack/Cargo.toml

... many more warnings ...

error: failed to select a version for the requirement `serde = "=1.0.130"`
candidate versions found which didn't match: 1.0.126
location searched: directory source `/data/users/wilfred/fbsource/fbcode/hphp/hack/.cargo_vendor` (which is replacing registry `crates-io`)
required by package `arena_collections v0.0.0 (/data/users/wilfred/fbsource/fbcode/hphp/hack/src/arena_collections)`
perhaps a crate was updated and forgotten to be re-vendored?
exit code 101 at line 67
```

See full output at P468900114.

Use the default profile instead.

Reviewed By: dtolnay

Differential Revision: D32607020

fbshipit-source-id: 758be860c91efe72bdd54d3e22c3f9608be328d3