fix OSS build error for undefined reference to softaes_block_encrypt
Summary:
While we are adding AEGIS implementation in D46231636, we did not add private/softaes.c to the
source file, causing undefined reference error as follows (https://fburl.com/2wfdpknc).

/usr/bin/ld: lib/libfizz.so.1.0.0: undefined reference to `softaes_block_encrypt'
collect2: error: ld returned 1 exit status

This change fixes the build error.

Reviewed By: therealgymmy, mingtaoy

Differential Revision: D46662195

fbshipit-source-id: 7af5b8aaf3af267f5fc4b12fc29914f75ddbf568