Refactor `expected` function argument in typing functions
Summary:
We use this `?expected` optional argument in our type checking of expressions that has type `(Pos.t * Reason.ureason * locl ty`. Because these are all mutually recursive functions, the OCaml type inference engine gives you a really hard time if you try to change this type. I started by adding type annotations to the functions where `?expected` and `~expected` appeared. Then, I changed the type to be a record instead of a tuple, and the error became
```
Error: This pattern matches values of type expected_ty option
       but a pattern was expected which matches values of type
         (Aast.pos * Reason.ureason * Typing_defs.locl Typing_defs.ty) option
       Type expected_ty is not compatible with type
         Aast.pos * Reason.ureason * Typing_defs.locl Typing_defs.ty
```
at the top of the `expr` function. I made all the `match expected with` expressions unbox records instead of tuples, but the error stayed the same and in the same position. I started manually changing the handwritten tuples into records wherever I found them. Eventually, the errors started happening inside the function bodies instead of at their signatures, and then I used them to fix the remaining spots.

With a declared record type, adding fields or changing this type should be far simpler. This refactor is similar to D13556386

Reviewed By: Matt-Schellhas

Differential Revision: D15370398

fbshipit-source-id: ef877cb7f4626098c81992b4bb9637f6e04132eb