Fix unused import in Rust fbthrift library
Summary:
```lang=log,counterexample
error: unused import: `crate::serialize`
  --> xplat/thrift/lib/rust/src/help.rs:46:5
   |
46 | use crate::serialize;
   |     ^^^^^^^^^^^^^^^^
   |
note: the lint level is defined here
  --> xplat/thrift/lib/rust/src/lib.rs:18:9
   |
18 | #![deny(warnings)]
   |         ^^^^^^^^
   = note: `#[deny(unused_imports)]` implied by `#[deny(warnings)]`
```

Reviewed By: cjlongoria

Differential Revision: D92236774

fbshipit-source-id: eee729d7567c1b695e53693e48d1a8960db40aa9