Fix autocargo by excluding fbcode/cli/rust/cli_main/integration
Summary:
Fixes:

```
$ fbcode/common/rust/cargo_from_buck/bin/autocargo
...
Error: While generating cargo files for targets path cli/rust/cli_main/integration/TARGETS

Caused by:
    0: While generating cargo manifest for TargetsPath { file: PathInFbcode("cli/rust/cli_main/integration/TARGETS"), dir: PathInFbcode("cli/rust/cli_main/integration") } in dir
 None
    1: In bin 'no-name' product generation
    2: Unable to find any of ["main.rs", "no_name.rs"] in ["no-name.rs"] while searching for crate root
```

Reviewed By: aorenste

Differential Revision: D36800262

fbshipit-source-id: 5334f6739efe666a5c1c88340596ba03db35ed81