Add a stress test for enum class autoloading issue
Summary:
Before paulbiss's diff, repeated execution of this test sometimes fails due to
race condition:

  done
  done
  done

  Fatal error: Undefined enum: ClsParent in stress-test-2.inc on line 4
  done
  done

  Fatal error: Undefined enum: ClsParent in stress-test-2.inc on line 4
  done
  done
  done

Reviewed By: 3ach

Differential Revision: D31680615

fbshipit-source-id: 1bc0c1673d2b33699a5150b148c0994840ed8fcf