Fix compile error in `BitSet<42>::hash()`
Summary:
While changing code in HHVM, I suddenly got this compile error:

```
hphp/util/bitset.h:173:43: error: array index 1 is past the end of the array (which contains 1 element) [-Werror,-Warray-bounds]
    size_t h = hash_int64_pair(m_data[0], m_data[1]);
                                          ^      ~
hphp/runtime/vm/jit/type-inl.h:175:14: note: in instantiation of member function 'HPHP::BitSet<42>::hash' requested here
      m_bits.hash(),
             ^
hphp/util/bitset.h:206:3: note: array 'm_data' declared here
  uint64_t m_data[M] = {0};
```

I believe the compiler is only sometimes complaining because the compiler usually doesn't take advantage of this method's `constexpr` declaration to evaluate this function at compile time.

We know that we won't go out of bounds at runtime, since we return earlier if `M == 1`. But I believe we need to hoist that check from runtime to compile time with `if constexpr` so the compiler can know this when evaluating the function at compile time.

Reviewed By: ricklavoie

Differential Revision: D23827509

fbshipit-source-id: f7aadc15358df7cc55dbb6e2e000a31ea67a8a4d